jaeyeon/greedy/1이될때까지.py, jaeyeon/greedy/숫자카드게임.py, jaeyeon/greedy/큰수의법칙.py
- 큰 수의 법칙
- 숫자카드 게임
- 1이 될 때까지
---
- 가장 큰 값과 그 다음 큰 값을 계속 더해줌
- 행마다 최소값 모아서 그 중 최대값 찾기
- 나누고 빼고를 반복!
---
=> [Greedy] 0313

yunjin/greedy/1이될때까지.py, yunjin/greedy/숫자카드게임.py, yunjin/greedy/큰수의법칙.py
- 큰수의법칙
- 숫자카드게임
- 1이될때까지
---
- 풀이과정
정렬 후에 큰값과 작은 값을 제한 값에 맞게 순서대로 나열하여 리스트를 리턴한 후 sum 처리
- 풀이과정
행 별로 최소값을 저장하는 리스트를 만들어 최대값을 리턴 해준다.
- 풀이과정
dp 방식으로 풀었다. i 번째의 최소값은 1) i-1 번째 +1 2) i/5 중에서 최소값이라고 생각했다. 하지만 i가 5의 배수인 경우와 아닌 경우를 한 번 더 구분해줬어야 했다.
---
=> [Greedy] yunjin-0313

jaeyeon/greedy/Q01-모험가길드.py, jaeyeon/greedy/Q02-곱하기 혹은 더하기.py
- 모험가 길드
- 곱하기 혹은 더하기
---
_그리디로 가능한 이유_
내림차순으로 정렬하여 앞에서부터 그룹을 이루면,
공포도의 크기가 인접한 사람들끼리 그룹을 이룰 것이다.
_풀이 순서_
1. 큰 순서대로 정렬
2. 앞에서부터 순회하며 공포도 X만큼의 사람을 연달아서 한 그룹에 넣을 수 있는지 확인
3. 가능하면 인덱스 + X, 불가능하면 인덱스 + 1
_그리디로 가능한 이유_
어떤 수에 0 또는 1을 곱하면 원래의 수보다 작거나 같아진다.
어떤 수에 1보다 큰 수를 곱하면 그 값은 원래 값보다 커진다.
-> 연산하려는 수에 0 또는 1이 있다면 서로 더해주고, 그 외의 경우 곱한다.
_풀이 순서_
1. 문자열을 정수 리스트로 변환
2. 첫번째 요소부터 순회하며 곱하기 혹은 더하기 진행
=> [Greedy] jaeyeon-0314

yunjin/greedy/곱하기혹은더하기.py, yunjin/greedy/모험가길드.py
- 모험가길드
- 곱하기혹은더하기
---
**모험가길드**
- 공포도가 낮은 것 부터 그룹을 나눠야 최대한 많이 나눌 수 있을거라고 생각했습니다.
- 그룹의 크기와 그룹내의 공포도 최댓값을 비교해서 그룹 크기가 더 커지는 순간에 새로운 그룹을 만드는 방식으로 처리했습니다.
**곱하기혹은더하기**
- 0을 곱하는 경우를 예외 처리해줬습니다.
- 초깃값이 0 이상이 되도록 해줬습니다.
- 더한 값과 곱한 값의 대소를 비교해서 큰 연산을 해주도록 처리해서 값을 구했습니다. 
---
=> [Greedy] yunjin-0314

dahye/greedy/3_1_모험가길드.py, dahye/greedy/3_2 곱하기 혹은 더하기.py
- 모험가 길드
- 곱하기 혹은 더하기
---
- 여행을 떠날 수 있는 그룹수의 최대값을 구해야하므로 가장 공포도가 큰 사람과 작은사람을 먼저 pop해주는 방식으로 그룹 수를 count
- 0을 제외한 나머지의 수는 곱하는 것이 가장 큰 수를 만들 수 있으므로 0이 아니고 result가 0이 아닐 때 곱하고 그 외에는 더하는 방식으로 result를 구함
---
=> [greedy] dahye-0314

youngjun/greedy/곱하기 혹은 더하기.py, youngjun/greedy/모험가 길드.py
- 문제 1 모험가 길드
- 문제 2 곱하기 혹은 더하기
---
- 공포도가 적은 사람부터 받아서 그룹을 만드는 것이 최대.
- 그룹에 새로 들어온 사람의 공포도와 그룹의 크기가 같다면 그룹을 만든다.
- 0,1 이면 더하고 나머지 숫자면 곱하는 것이 최대
- 처음 들어오는 숫자가 0이 아닐 때 까지 더하고 나머지는 위의 규칙
---
=> [Greedy] 0314

jaeyeon/greedy/Q03-문자열 뒤집기.py, jaeyeon/greedy/Q04-만들 수 없는 금액.py
- 문자열 뒤집기
- 만들 수 없는 금액
---
_그리디로 가능한 이유_
숫자를 뒤집는 모든 경우를 탐색하는 것이 아닌,
연속한 숫자가 몇 번 반복되는지 나눠서 구하였다.
한 번의 뒤집기에서 연속한 숫자만 뒤집을 수 있으므로
연속한 숫자의 개수가 곧 뒤집기의 횟수이기 때문에,
그리디한 해법이 가능하다.
- 풀이과정
1. 1을 기준으로 문자열을 split하여 0으로만 이루어진 리스트를 구한다
`"0011000" -> ["00","","000"]`
2. 0을 기준으로 문자열을 split하여 1로만 이루어진 리스트를 구한다.
`"0011000" -> ["","11",""]`
3. 두 리스트에서 0이 아닌 요소의 개수를 비교하여, 더 작은 수를 답으로 한다.
_그리디로 가능한 이유_
먼저, 만들 수 없는 최소 금액을 찾아야하기 때문에, 만드는 수 자체는
최소값부터 완전 탐색을 통해 찾아야 한다고 생각했다.
수를 만드는 과정에서 그리디한 해법이 가능하다고 생각한다.
큰 값을 먼저 더해주는 식으로 진행하였다.
- 풀이과정
1. 반복문을 통해 만들어야 하는 수를 1부터 오름차순으로 탐색한다.
2. 정렬된 동전 리스트(`coins`)에서 큰 값을 먼저 더하며 특정 수(`target`)를 만든다.
3. 동전 리스트의 모든 값을 순회했음에도 특정 수를 못 만들면, 플래그(`isAble`)를 사용하여 반복문을 끝낸다
=> [Greedy] jaeyeon-0315

만들 수 없는 금액.py, 문자열 뒤집기.py
- 문제 1 문자열 뒤집기
- 문제 2 만들 수 없는 금액
---
첫번째 문자에서 다른 것으로 바뀐 개수를 찾는 문제라 생각함
0으로 시작할 때 1로 바뀌는 개수는 '01' 의 개수
1로 시작할 때 0으로 바뀌는 개수는 '10'의 개수
이진법으로 해결하려다 도저히 생각이 안나서 결국 다 찾는 방식으로 진행함
itertools.combinations를 사용하여 모든 금액을 찾아서 안나온 최소 금액을 찾는 방식
combinations를 사용하여 n이 조금만 커져도 에러 발생
=> [greedy] youngjun 0315

dahye/greedy/3_3_문자열뒤집기.py, dahye/greedy/3_4_만들수없는금액.py
- 문자열 뒤집기
- 만들 수 없는 금액
---
- 맨 처음 숫자를 기준으로 바뀌는 횟수를 체크
- 바뀌는 횟수가 짝수(n)개이면 뒤집어야 할 수는 n/2 or n/2+1이므로 n/2 출력
- 바뀌는 횟수가 홀수(m)개이면 뒤집어야 할 수는 (m+1)/2이므로 (m+1)/2 출력
- data를 크기순으로 sort하여 temp로 현재 동전까지로 만들 수 있는 금액을 update
- 이때 다음 동전의 크기가 temp보다 클 때 temp를 만들 수 없으므로 temp를 출력
---
=> [Greedy] dahye-0315

yunjin/greedy/만들 수 없는 금액.py, yunjin/greedy/문자열 뒤집기.py
- 문자열 뒤집기
- 만들 수 없는 금액
---
문자열 뒤집기
- 0, 1 밖에 없으므로 바뀌는 구간을 체크해줍니다.
- answer 가 짝수라는 것은 주어진 값이 홀수 영역으로 나뉘어진다는 것이고 answer 가 홀수라는 것은 주어진 값이 짝 수 영역으로 나뉘어진다는 것입니다. (ex. answer= 3 -> 0101 -> 4개로 나뉘어짐)
- 짝수면 2로 나눈값을 홀수면 2로 나눈값의 버림에 +1 을 더해줍니다.
만들 수 없는 금액
- 한참동안 풀었다.
- 먼저 주어진 동전들을 오름차순 정렬
- check_list를 복제해서 동전 중 최솟값 더한 값을 넣을 만든다. 새로운 check_list는 복제된 check_list 에 동전 최솟값을 넣어준게 된다.  ->  이렇게 하게 되면 동전으로 만들 수 있는 조합들을 작은 값부터 체크해나갈 수 있다. (시간복잡도 n^2 = 1000000)
- start_number = 1 부터 set in 함수로 체크해나간다. (시간복잡도가 O(1) )
- 만들 수 없는 금액에서 시간복잡도가 n^2 으로 계산 되는게 맞는지 잘 모르겠습니다.
=> [Greedy] yunjin-0315

jieun/greedy/Q01_모험가길드.py, jieun/greedy/Q02_곱하기혹은더하기.py, jieun/greedy/Q03_문자열뒤집기.py, jieun/greedy/Q04_만들수없는금액.py
- 문자열 뒤집기
- 만들 수 없는 금액
---
0으로 이루어진 구간의 개수와 1로 이루어진 구간의 개수를 구하고, 구간 개수가 최소인 종류를 뒤집는다.
1에서 순서대로 보며 만들 수 없는 값을 찾는다.
- 동전 `coin`이하의 동전들만 고려해서 n을 만들려고 하자. 1 ~  (n-1)은 이미 만들 수 있다.
- `start`는 `coin` 전 동전들로 만들 수 없는 값의 최소이다. 즉, `coin`을 꼭 사용해야 하는 값의 최소이다.
- $n = coin + j \\; (n >= coin)$일 때:
- $0 <= j < start$ 이면 만들 수 있다.
- $j >= start$이면 `coin` 이하 동전들로는 만들 수 없다. 그러므로 `coin` 다음 동전을 보기 시작한다. 
- 이때, $다음\\,동전 > n$ 이면 n을 만들 수 없다.
---
=> [Greedy] jieun-0315

youngjun/greedy/무지의 먹방 라이브.py, youngjun/greedy/볼링공 고르기.py
- 볼링공 고르기
- 무지의 먹방 라이브
---
- 모든 조합에서 같은 볼링공을 고르는 경우를 빼는 방식
- 같은 무게인 공에서 2개씩 조합을 이루는 경우들을 빼줌
- 남은 시간동안 0이 아닌 음식들을 몇바퀴 돌 수 있는지 보고 음식에서 그만큼 빼기
- 빼줬을 때 음수의 경우 : 음수들을 모두 더해서 위에서 사이클을 돌리고 남은 시간에 추가
- 위의 두 과정을 반복
- 결국 한 사이클을 못돌리는 시간이 나옴
=> [Greedy] youngjun-0316

yunjin/greedy/Q5 볼링공 고르기.py, yunjin/greedy/Q6 무지의 먹방 라이브.py
- 볼링공 고르기
- 무지의 먹방 라이브
---
- Counter 를 이용해서 동일 무게 있는 것들을 세주고, sort 로 작은것부터 정렬한다.
- 중복되지 않으면서 다른 무게들의 조합은. 위에서 구한 자기 보다 큰 무게인 볼링공의 수 * 본인과 같은 무게의 수
- 진행하면서 카운트한 볼링공은 길이에서 제거함으로써 중복을 피할 수 있음.
- 일단 시간 복잡도를 해결 할  수 있는 아이디어가 떠오르지 않았다.
- 그래서 단순 반복문으로 풀었다.
- 이마저도 정확성 테스트를 통과하지 못했다.
- 그래도 제가 생각한 풀이를 적어보자면.  남아있는 음식의 최솟값 * (그 이상의 음식들 길이 수) 를 계속해서 k 에서 빼준다. `k <= l or k <= min(food_times) or k <= l * min(food_times)` 인 경우에 반복문을 탈출해서 어느적도 작아진 k 에 대해서 경우의 수를 다시 따져가며 k = 0 을 만들려고 했습니다. 그러다보면 언젠가 `k == 0`  이 분명 될거라고 생각했다. 
- 그런데 정확성 테스트도 통과하지 못했습니다.
- 그래서 해답지를 봤습니다. `heapq` 라이브러리를 사용했고, 정렬과 나눗셈을 이용해서 index 를 구한 걸 확인했습니다. 
- 오답 풀이여서 자세히 안보셔도 될거 같습니다. 코드가 알아보기가 힘드네요.
---
=> [Greedy] yunjin-0316

jaeyeon/greedy/Q05-볼링공 고르기.py, jaeyeon/greedy/Q06-무지의 먹방 라이브.py
- 볼링공 고르기
- 무지의 먹방 라이브
---
- 풀이과정
1. 각 무게 별로 볼링공의 개수 세기
2. 가능한 모든 볼링공의 조합 수 구하기
3. 같은 무게로 만드는 볼링공의 조합 수 제외하기
- O(N^2) 풀이과정
1. `k`초 안에 모든 음식을 먹을 수 있다면 -1 반환
2. `time_list`에 음식을 먹는 순서대로 append
3. `time_list[k]` 구하기
- O(N) 풀이과정
1.`k`초 안에 모든 음식을 먹을 수 있다면 -1 반환
2. `k`를 `food_times`의 길이 `N`으로 나눠 몫(step)과 나머지(index)구하기
3. `food_times`의 모든 값을 `left_list`에 인덱스와 값을 함께 저장
4. `left_list`에서 모든 음식의 값에서 `step` 빼기
5. 값이 0보다 큰 요소만 새로운 `left_list`에 추가, 값이 0보다 작다면 작은 만큼 `index_add`에 추가
6. step과 index를 업데이트 
7-1. step이 0이 아니라면 4번 과정으로 돌아가서 반복
7-2. step이 0이라면 left_list에서 index만큼 음식 먹는 과정 진행 
글로는 복잡해서 부연 설명을 위해 사진 또한 첨부합니다.
1. 초기 상태
2. step만큼 전체에서 뺀 상태
3. 만들어진 left_list에서 값 찾기
---
- 2번 문제 같은 경우, 효율성 테스트는 O(N), O(NlogN)이 아닌 이상 문제가 풀리지 않을 것으로 보입니다. 2번 문제의 두번째 풀이에서는 시간 초과는 안 나지만 인덱싱에서 문제가 생긴건지, 정확도가 많이 떨어집니다. …
=> [Greedy] jaeyeon-0316

dahye/greedy/3_5_볼링공고르기.py, dahye/greedy/3_6_무지의먹방라이브.py
- 문제 1 볼링공 고르기
- 문제 2 무지의 먹방 라이브
---
- 무게가 같은 공의 개수를 구한 후
- 전체 조합 수를 factorial함수를 이용하여 구하고
- 무게가 같은 공의 조합 수를 전체에서 뺀다.
- for문으로 food_times의 값을 1씩빼주면서 순회하고,
- 0이면 다음 차례의 값을 1만큼 빼주면서 현재 먹는 접시를 update해준다.
- 다음에 먹을 접시를 구하는 것이므로 마지막 접시에서 +1만큼의 값을 print한다.
---
=> [Greedy] dahye-0316

jieun/greedy/Q05_볼링공고르기.py, jieun/greedy/Q06_무지의먹방라이브.py
- 볼링공 고르기
- 무지의 먹방 라이브
---
- 볼링공 무게의 조합을 구한다. 
- 무게 조합 경우에 대해 해당하는 볼링공 번호의 조합 개수를 구한다.
예를 들어 무게 조합 (1,2)이 있으면, 무게가 1인 공의 개수와 무게가 2인 공의 개수를 곱하면 된다.
남은 음식이 감소하는 값을 같게 하기 위해서 바퀴 단위로 탐색한다. 그러면 처음에 다 먹는데 필요한 시간 기준으로 정렬한 순서를 바꾸지 않아도 된다.
한 바퀴를 탐색한다. 
한 바퀴에 걸린 시간 t가 `t <= k`이면 남은 음식의 수를 갱신하고, 리스트에서 다 먹은 음식을 제거한다. k에서 걸린 시간을 빼고 탐색을 계속한다.
`t > k`이면 남은 음식 앞에서부터 순회하면서 k를 하나씩 감소시킨다. k=0일 때 먹는 음식을 찾는다.
💡 `t == k` 일 때? 한 바퀴 돌리고 장애가 발생하는 경우이다. 다음 단계에서 k=0이 되므로 예외로 처리 안 해도 해결된다.
시간 초과가 날 것 같다.
한 바퀴 대신 여러 바퀴를 한꺼번에 처리하자. 
지금까지 `pre` 바퀴를 돌았다고 하자.
남은 음식 중 필요시간이 가장 적은 음식을 다 먹는데 필요한 바퀴수는 `(필요시간 - pre)` 이다.
이때, 필요시간이 같은 음식들은 같은 바퀴에서 다 먹는다.
남은 음식 개수가 n이면, 추가로 걸린 시간 T는 `T =  n x (필요시간-pre)`
`T <= k`이면 필요시간이 같은 음식들의 개수(a)를 구한다. *n &larr; n - a, k &larr; k - t*로 갱신한다.
`T > k` 이면 위와 같다. 남은 음식을 하나씩 순회하면 시간 초과가 날 것 같다. …
=> [Greedy] jieun-0316

jaeyeon/구현/게임개발.py, jaeyeon/구현/왕실의나이트.py
- 왕실의 나이트
- 게임 개발
---
- 풀이과정
반복문을 통해 나이트의 다음 위치가 체스판 내에 있는지 확인하며 카운트합니다.
- 풀이과정
1. 시뮬레이션 국룰 dr, dc(또는 dx, dy)를 문제에 주어진 동서남북 방향과 맞게 세팅합니다.
2. 방문한 지점은 다시 방문 못하므로 바다와 똑같이 취급합니다.
3. 문제에 주어진 조건들을 매번 확인하며 코너 케이스가 발생하지 않도록 진행합니다.
4. 자세한 진행 방식과 조건들은 코드에 주석으로 세세하게 달아놨으니 참고해주세요.
처음으로 시간을 정해두고 풀어보았는데, 
꽤나 스릴 있고 좀 더 효율적으로 코드를 짜려고 생각하는 것 같습니다.
추천드려요!
---
네 방향 모두 돌고 나서는 뒤 칸이 바다일 때만 코드가 멈추는거였군요,,!
방문한 칸을 1이 아닌 2로 업데이트 하는 식으로 코드를 바꾸겠습니다 하핳
=> [구현] jaeyeon-0320

jieun/구현/게임개발.py, jieun/구현/왕실의나이트.py
- 왕실의 나이트
- 게임 개발
---
- 나이트가 이동 가능한 행,열 조합을 구한다.
- 각 조합에 따라 이동한 칸이 체스판 안에 있는지 확인한다.
- 바라보는 방향에 따라 이동하는 행,열 조합을 구한다.
- 문제에 나와있는 매뉴얼 그대로 구현한다.
- $다음 \\; 방향 = (현재 \\; 방향 - 1 + 4) \\; \\% \\; 4$
- $뒤쪽 \\; 방향 = (현재 \\; 방향 + 2) \\; \\% \\; 4$
**(추가)** 뒤로 이동할 때에도 이미 방문한 칸은 못 간다고 가정한 틀린 풀이입니다.
문제를 다시 읽어보니 뒤쪽 방향은 바다만 아니면 갈 수 있었군요;; @hoooolllly 님 덕분에 깨달았습니다.
나중에 수정한 풀이 커밋하겠습니다.
---
=> [구현] jieun-0320

yunjin/greedy/Q6 무지의 먹방 라이브.py, yunjin/implementation/게임 개발.py, yunjin/implementation/왕실의 나이트.py
- 왕실의 나이트
- 게임 개발
---
- `ascii_lowercase` 라이브러리로 영어 소문자를 숫자로 매핑해주는 방식으로 풀었습니다.
- 맵 밖으로 나가는 것을 체크해줬습니다.
- 북서남동 이동 배열을 move_row, move_column 으로 만들었습니다.
- `visit `배열을 만들고 (바다, 방문 한 경우는 True) 갈 수 있는 지 여부를 체크해줬습니다. 
- `STEP1`을 해주고 북서남동 체크를 해줬습니다. 다 막혀있다면 방향을 원래 보던 방향으로 바꾸고 뒤로 가게 해줬습니다.`(STEP3) `
- 갈 수 있는 공간이 있고 그곳이 육지라면 이동시켜줬습니다.`(STEP2)` (이 때 뒤로 이동하다가 새로운 곳을 밟은 경우도 체크해줬습니다.)
- 주의해야 할 점으로 시뮬레이션 종료 조건은 `뒤로 이동하다가 바다를 본경우`라는 것이고`(STEP3)` 이 부분에 유의해서 풀어보았습니다.
---
=> [구현] yunjin-0320

youngjun/구현/게임 개발.py, youngjun/구현/왕실의 나이트.py
- 문제 1 왕실의 나이트
- 문제 2 게임 개발
---
- 나이트가 이동했을 때 나올 수 있는 x,y 좌표 변화량 list 생성
- 총 8개의 이동에서 체스판 밖으로 나가는 이동일 시 답에서 -1
- 움직였을 때 좌표 변화량 리스트 생성(방향 숫자가 인덱스)
- 맵 크기 만큼 visit 영행렬 생성 (시작 좌표 1로 변경)
- 1단계 부터 조건에 맞게 코드 작성
- 이동한 장소 좌표를 visit 행렬에 1로 표기
- while 문을 통해 1단계로 돌아가는 과정 및 종료 시 break 통해서 멈춤
- visit 행렬에서 1 개수 return
(추가)동서남북 방향 숫자를 잘못적어서 정답이 제대로 안나옵니다 남북 바꿔야 됩니다
=> [구현] youngjun-0320

dahye/구현/2_2_왕실의나이트.py, dahye/구현/2_3_게임개발.py
- 문제 1 왕실의 나이트
- 문제 2 게임 개발
---
- 가능한 이동의 총 경우의 수 8에서 나이트의 위치에 따라 불가능한 이동만큼 빼주는 방식으로 풀이하였습니다. 
- 계속 시도중인데, 코드는 길어지는데 오류가 발생합니다.... 일단 계속해서 풀어보겠습니다! 아직 미완성 코드이니 따로 코멘트 안해주셔도 될 것 같습니다.
---
=> [구현] dahye-0320

jieun/구현/Q07_럭키스트레이트.py, jieun/구현/Q08_문자열재정렬.py, jieun/구현/게임개발.py
- 럭키 스트레이트
- 문자열 재정렬
---
- 입력을 정수 리스트로 변환한다.
- 점수의 길이의 반을 `half`라고 하면, 왼쪽 부분의 인덱스 구간은 [0,`half`-1], 오른쪽 부분은 [`half`, 끝] 이다.
- 왼쪽 부분의 합과 오른쪽 부분의 합을 비교한다.
- 입력의 각 문자를 보면서 알파벳 대문자이면 `letters`에 저장하고, 숫자이면 `num`에 값을 더한다.
- `letters`를 오름차순으로 정렬한다.
- 정렬된 `letters`를 문자열로 만든 후, 뒤에 num을 문자열로 변환해서 이은다.
---
=> [구현] jieun-0321

yunjin/implementation/Q7 럭키 스트레이트.py, yunjin/implementation/Q8 문자열 재정렬.py
- 럭키스트레이트
- 문자열 재정렬
---
- 풀이과정
절반 왼쪽합과 절반 오른쪽 합을 구해서 대소 비교를 한다.
- 풀이과정
숫자를 따로 더한 것을 변수에 저장합니다.
남은 문자열을 더해주고 숫자를 더해서 출력한다.
---
=> [구현] yunjin-0321

dahye/구현/4_Q07_럭키스트레이트.py, dahye/구현/4_Q08_문자열재정렬.py
- 문제 1 럭키 스트레이트
- 문제 2 문자열 재정렬
---
- map함수를 이용해 데이터를 하나하나씩 list에 int로 저장
- index slicing으로 절반씩 더해주기
- map함수를 이용해 데이터를 하나하나씩 list에 int로 저장
- sort로 숫자 -> 문자순으로 정렬
- 가장 앞의 값이 숫자이면 문자가 나오기 전까지 result에 더해주면서 pop
---
=> [구현] dahye-0321

jaeyeon/구현/Q07-럭키 스트레이트.py, jaeyeon/구현/Q08-문자열 재정렬.py
- 럭키 스트레이트
- 문자열 재정렬
---
- 풀이과정
1. 중간을 기준으로 입력 받은 문자열을 슬라이싱합니다.
2. 각각의 리스트를 정수 리스트로 캐스팅하고, 각각의 합을 구합니다.
3. 값을 비교하여 그에 맞게 출력합니다.
- 풀이과정
1. 알파벳만 담은 배열을 생성하고, 정렬 후, 다시 문자열로 만들어둡니다.
2. 정수만 담은 배열을 생성하고, 그 과정에서 정수로 캐스팅 후 배열의 합을 구합니다.
3. 문자열과 정수를 f string을 활용해 답변 스트링으로 합쳐줍니다.
이번 문제들은 문자열을 다루는 방법들이 각자 달라서, 
서로 어떤 방법을 사용했는지 공유하는 것이 주안점일 것 같습니다.
다른 분들의 풀이도 궁금하네요!
---
=> [구현] jaeyeon-0321

youngjun/구현/럭키 스트레이트.py, youngjun/구현/문자열 재정렬.py
- 럭키 스트레이트
- 문자열 재정렬
---
- 입력받은 정수를 문자로 바꾸고 for 문을 돌림
- 앞부분은 front 변수에 더하고 뒷부분은 back 변수에 더함
- 두 변수를 비교하여 정답 리턴
- 입력받은 문자열을 isdigit()을 통해 문자,숫자 리스트로 나눔
- 문자 리스트는 정렬, 숫자 리스트는 더해서 문자리스트 뒤에 추가
- join을 통해 문자열로 리턴
=> Youngjun 03 21

jieun/구현/Q09_문자열압축.py, jieun/구현/Q10_자물쇠와열쇠.py
- 문자열 압축
- 자물쇠와 열쇠
---
1. 압축시킬 단위를 1에서 주어진 문자열 길이까지 순서대로 본다.
2. 해당 단위에 대해 압축 문자열을 생성한다. 
3. 만든 압축 문자열의 길이와 답을 비교해서 더 작은 것으로 갱신한다.
1. 열쇠를 한 칸씩 움직이면서 자물쇠와 맞물리는지 확인한다. 
2. 해당 자물쇠 위치에 대해 자물쇠 칸을 하나씩 확인한다. 
- 해당 칸이 열쇠와 겹쳐있는데, 같은 값이면 맞물리지 않는다.
- 해당 칸이 열쇠와 겹쳐져 있지 않는데, 자물쇠 칸이 홈이면 맞물리지 않는다.
3. 열쇠를 시계방향으로 회전시키고 1번을 반복한다.
- **확장판**: 자물쇠를 가운데에 고정시키고, 
열쇠의 일부분이 자물쇠와 겹치는 한에서 최대한 멀리 떨어뜨린 모든 경우를 합친 그리드를 의미한다.
---
=> [구현] jieun-0322

yunjin/implementation/Q10 자물쇠와 열쇠.py, yunjin/implementation/Q9 문자열 압축.py
- 문자열 압축
- 자물쇠와 열쇠
---
- 풀이과정
1. 문자열을 몇 칸 별로 이동 할 건지 i 칸 씩 for 문을 돕니다.
2. 각 i 에 대해서 반복문을 돌면서 문자열이 어떻게 생성되는 지 만들어주고 길이를 보관합니다.
3. 최소값 리턴해줍니다.
- 풀이과정
1. 자물쇠 크기를 자물쇠 크기 만큼 확장시켜 줍니다. -> `3*len(lock)`
2. 원본 자물쇠의 왼 맨쪽 최상단 부터 완전탐색을 해줍니다. (0, 90, 180, 270) 도 회전해주면서(`rotate_2d`) 체크해줍니다.
3. 자물쇠의 모든 영역이 1 로 되었을 때만이 열쇠가 열린다는 것을 check 함수로 확인해줍니다.(`check`)
---
=> [구현] 최윤진-0322

youngjun/구현/문자열 압축.py, youngjun/구현/자물쇠와 열쇠.py
- 문자열 압축
- 자물쇠와 열쇠
---
- 한글자 단위부터 (문자열 길이//2) 단위까지 다 끊어서 확인
- 각 단위가 뒤와 같은 지 확인 후 같다면 cnt를 올려서 숫자로 대신 표현
- 모든 경우의 길이를 비교 후 제일 작은 값을 리턴
- 자물쇠에 열쇠만큼 패딩을 시켜줌 -> 열쇠가 나가있는 경우를 해결 가능함
- 열쇠를 회전하는 경우 -> 4번 반복
- 열쇠를 0,0부터 한칸 이동시키고 더해줌
- 만약 원래의 자물쇠 부분이 다 1이라면 True 리턴 아니면 다시 자물쇠를 초기화 시키고 위 과정 반복
- 모든 경우 다 없으면 False 리턴
---
- 2번 문제에서 copy를 써서 자물쇠를 초기화 시켰을 때는 안 됐는데 deepcopy쓰니까 초기화가 됨
- 왜 copy로는 안됐는지 궁금합니다
---
=> [구현] youngjun-0322

dahye/구현/4_Q09_문자열압축.py, dahye/구현/4_Q10_자물쇠와 열쇠.py
- 문제 1 문자열 압축
- 문제 2 자물쇠와 열쇠
---
- 1씩부터 하나하나 반복기준으로 하여 result에 추가하면서 가장 짧은 표현의 길이를 return
- rotation함수를 생성하여 90도 회전하는 기능을 추가하고 check함수로 Lock 안의 모든 수가 1인지 여부를 확인한다.
- 이때, 영역을 벗어나도 되므로, pooling(0)으로 가장자리를 채워주어, key를 한칸씩 아래,옆으로 이동하면서 확인한다.
- 다 된것 같으면서도 자꾸 원하는 형식으로 출력이 안되어 이것저것 고치다보니 코드를 이해하기 어려우실 것 같습니다. 풀이 방법만 간단히 봐주세요!
- check하는 과정에서 array와 list를 비교할 수 없어 여러가지 추가를 하였는데, 어느부분에서 잘못된건지 원하는 출력값이 안나옵니다. 중간에 고쳐야할 부분이 필요한 코드입니다~.. 머리좀 식히고 천천히 고쳐야할 것 같아요 ㅎㅎ
---
=> [구현] dahye-0322

jaeyeon/구현/Q11-뱀.py
- 뱀
---
- 풀이과정
1. 사과의 인덱스를 고려해서 `(N+1)X(N+1)` 크기의 보드 생성
2. 회전해야하는 시간과 방향을 검색이 용이하도록 dict 형태로 저장, L과 D를 각각 반시계, 시계라 생각하고 -1와 1로 저장
3. 반시계, 시계 방향과 현재 방향을 고려하여 dr, dc 생성
4. 반복문 시작할 때 시간 +1 하고 다음 좌표 계산
5. 다음 좌표가 몸이랑 겹치는지, 범위를 벗어나는지 확인 -> 조건에 부합하지 않으면 break
6. 일단 몸을 늘리므로, 다음 좌표를 snake 배열 처음에 insert
7. 다음 좌표가 사과면 사과칸 0으로 만들고, 아니면 snake 배열의 마지막 요소 삭제
8. 현재 위치
9. X초가 끝났으므로 회전 여부 확인 및 dict에 있을 시 회전
=> [구현] jaeyeon-0323

jieun/구현/Q11_뱀.py
- 뱀
---
1. N x N 리스트 `board`를 선언하고 `0`으로 초기화한다.
2. 사과가 있는 위치를 입력 받아 `board`에 `1`을 저장한다.
3. `dir`에 뱀의 방향을 저장하고, `snake` 리스트에 `[꼬리, ..., 머리]` 순으로 뱀이 있는 칸을 저장한다. 뱀이 있는 `board`칸에는 `2`를 저장한다.
4. `change`에 방향 전환을 입력받아 저장한다.
5. `time`을 하나씩 늘려나가면서 루프를 돈다.
1. 뱀의 머리가 이동할 칸을 구한다. 벽이나 자기 몸을 만나면 루프를 벗어난다.
2. 사과가 없는 칸이면 `snake`와 `board`에서 꼬리를 제거한다.
3. `snake`와 `board`에 뱀의 머리를 추가한다. 
4. 방향을 전환할 시간인지 확인하고, 맞다면 전환한다. 전환한 방향은 `change`에서 제거한다.
---
=> [구현] jieun-0323

yunjin/implementation/Q11 뱀.py
- 뱀
---
- 풀이과정
1. `snake_able_map` 은 `뱀이 갈 수 있는 영역`을 표시하였고, `apple_map`변수로  `사과 영역`을 표시 했습니다.
2. `trace` 변수를 선언해서 `뱀의 현재 위치`를 표시해줬습니다.
3. 사과를 먹었다면 `trace` 에 쌓기만 하고, 안 먹었다면 `trace` 에서 처음에 넣은 것을 삭제하는 방향으로 뱀의 이동을 체크해줬습니다.
=> [구현] yunjin-03-23

youngjun/구현/뱀.py
- 뱀
---
- 머리 방향에 따라 변하는 좌표 크기 만들어 놓고
- 회전 할때 time이 되면 방향 바꿔서 이동하는 방식
- 몸통 리스트를 만들어서 시작좌표를 넣어두고 이동 후 머리 좌표를 append해준다
-  사과를 먹지 않았으면 pop(0)을 통해 꼬리 지워주고 사과를 먹었으면 지우지 않는다.
- 머리가 움직였을 때 벽에 부딪히거나 움직인 좌표가 몸통 리스트에 있으면 time 리턴
=> [구현] youngjun-0323

dahye/구현/4_Q11_뱀.py
- 문제 1 뱀
---
- 한칸한칸 이동하면서 보드의 숫자를 바꿈 (뱀 2, 사과 1, 나머지1)
- 사과가 있으면 뱀 위치 추가 없으면 꼬리를 자르고 뱀 위치 추가
- 자신의 몸과 마주치거나(2) 보드를 넘어가면 break
- 현재 방향과 회전으로 다음 방향을 결정
- step을 할때마다 count로 초를 셈
---
- test case 2번을 자꾸 틀리네요 ㅠㅠ 아무리 봐도 모르겠습니다..
---
=> [구현] dahye-0323

yunjin/implementation/Q12 기둥과 보 설치.py
- 기둥과 보 설치
---
- 풀이과정
- 안 풀려서 솔루션 참고해서 풀었습니다.
- 추가, 삭제 할 때마다 is_normal 함수를 이용해서 해당 행동이 허용 될 수 있는 지 확인합니다. 비정상이라면 원복합니다. 이때 is_nomal 함수는 전체 맵을 검사합니다.
=> [구현] yunjin-0324

dahye/구현/4_Q12_기둥과 보 설치.py
- 문제 1 기둥과 보 설치
---
- 추가(삭제)일 때 temp_list에서 추가(삭제)하여 check함수로 추가(삭제)가능여부를 return하여 temp_list(answer)를 구한다. 
- 만약 불가능하다면 다시 삭제(추가)하기
---
욕심부리다가 제출시간을 많이 넘겨버렸네요.. 죄송합니다.
---
=> [구현] dahye-0324

youngjun/구현/기둥과 보 설치.py
- 기둥과 보 설치
---
- 각 좌표마다 빈 리스트를 생성해서 기둥 설치 및 삭제: 해당 좌표, y+1 좌표 0 추가 및 삭제, 보 설치 및 삭제:  해당 좌표, x+1 좌표 1 추가 및 삭제
- 설치 조건이 되면 설치
- 삭제 조건이 되면 삭제
---
- 삭제 가능한 경우를 생각하다가 계속 꼬여가지고 코드만 길어지고 정작 해결은 안돼서 삭제 부분은 안보셔도 될 것 같습니다. 
- 조건식에 어떤 것은 map_ 어떤 것은 answer을 썼는데, 처음엔 map_만 조건으로 쓰다가 도중에 바꾼 것이라 왔다갔다 합니다.
- answer만 써서 조건 정하는 것이 더 깔끔한 방법 같습니다!
- 프로그래머스 돌려보면 테스트 1,2 만 통과하고 제출하면 거의 다 틀립니다.
---
=> [구현] youngjun-0324

jieun/구현/Q12_기둥과보설치.py
- 기둥과 보 설치
---
- `map_`은 교차점을 하나의 칸으로 본다. ⚠️ `map_[x][y]`는 가로 x, 세로 y의 값이다.
- 패딩을 적용해서 좌표는 다음과 같이 변한다:
|문제 좌표|패딩|0|1|...|n-1|n|패딩|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|패딩 좌표|0|1|2|...|n|n+1|n+2|
- `map_`의 값은 다음과 같다:
|패딩|빈 칸|보|기둥|보+기둥|
|:---:|:---:|:---:|:---:|:---:|
|-1|00|01|10|11|
즉, `% 10 == 1` 로 보가 있는지 확인하고, `// 10 == 1`로 기둥이 있는지 확인한다.
- `is_ok(x,y,obj)`로 (x,y)에 obj가 있어도 되는지 확인한다. (x,y)에 obj가 없을 때는 True를 반환한다.
- `build_frame`에 있는 행동을 하나 수행한다. 
- 설치했으면 `is_ok()`로 그 행동이 조건을 만족하는지 확인한다. 
- 삭제했으면 영향을 받는 주변 칸들에 대해 `is_ok()`를 수행해서 주변 칸들이 여전히 조건을 만족하는지 확인한다.
조건을 만족하지 않으면 원상복구한다.
- 문제에 주어진 순서대로 `map_`을 돌면서 기둥과 보를 찾는다.
**(추가) [기둥 또는 보와 영향을 받는 주변 칸들]**
---
=> [구현] jieun-0324

jaeyeon/DFSBFS/미로 탈출.py, jaeyeon/DFSBFS/음료수 얼려 먹기.py
- 음료수 얼려 먹기
- 미로 탈출
---
- 풀이과정
1. 붙어있는 영역을 모두 탐색해야하므로 깊이 우선 탐색 방식 사용
2. 전체 틀에서 값이 0인 곳에서 DFS 실행
3. 인접한 칸이 0이라면 재귀적으로 DFS가 실행되고 방문 지점을 1로 업데이트
4. 최상위 DFS가 한 번 끝나면 하나의 얼음이 만들어지므로 1 반환
- 풀이과정
1. 출구까지의 최단 거리를 찾아야하므로 BFS 사용
2. queue에 현재 지점과 현재의 depth를 append. 여기서의 depth는 출발지점부터 그 지점까지의 최단 거리를 뜻함
3. BFS 실행 과정에서, 현재 지점의 값이 1이라면 처음 방문한 칸이라는 뜻이므로 depth로 업데이트
4. 방문하지 않은 칸이 있다면, queue에 그 칸의 행, 열, depth+1 을 업데이트
5. 다음 칸이 출구라면 현재 칸의 depth를 print 하고 종료
++ 방문 지점의 값이 1인 경우 depth를 업데이트 하다보니, 시작 지점이 3으로 업데이트 되는 문제가 있어, 이를 예외처리 해주었습니다.
++ 이중 반복문의 탈출을 위해 answer의 값이 업데이트 되면 종료하도록 하였습니다.
=> [DFS/BFS] jaeyeon-0327

dahye/DFS_BFS/5_3_음료수얼려먹기.py, dahye/DFS_BFS/5_4_미로탈출.py
- 문제 1 음료수 얼려먹기
- 문제 2 미로 탈출
---
- 0의 끝을 탐색할 때까지 재귀함수 사용하기 위해 dfs 함수 정의
- 상하좌우로 이동하면서 0이 더이상 없을 때 까지 재귀
- 미로를 탈출할 때까지 재귀함수 사용하기 위해 dfs 함수 정의
- n-1,m-1에 도달할때까지 계속 진행 
- n-1,m-1에 도달하지 않은 채로 범위를 넘어가면 미로를 탈출한 것이 아니므로 무시
---
- 문제 2번 풀이중에 이중 for문 break를 쓰는 과정에서 SyntaxError가 발생해서 해결을 못했는데, 해결 후 피어세션 시간에 다시 공유하겠습니다!
- 문제 1번의 원래 풀이는 다음과 같았는데, count를 함수안에서 또 정의를 해주어야해서  재귀할 때 reset이 되어 잘못된 풀이라 모범답안을 참고하였습니다.
```
def dfs(x,y) :
if x>=n or x<0 or y>=m or y<0: #범위넘어가면 멈춤
return ''
while True:
if data[x][y] == 0: #상하좌우로 이동
data[x][y] = 1 # 방문처리
dfs(x+1,y)
dfs(x-1,y)
dfs(x,y+1)
dfs(x,y-1)
elif temp == 'continue':
dfs(x+1,y)
dfs(x-1,y)
dfs(x,y+1)
dfs(x,y-1)
else :
temp = 'stop'
count += 1
break
return count
print(dfs(0,0))
```
---
=> [DFS_BFS] dahye-0327

yunjin/DFSBFS/Q15 특정 거리의 도시 찾기.py, yunjin/DFSBFS/Q16 연구소.py
- 특정 거리의 도시 찾기
- 연구소
---
- 인접 리스트를 만들어서 BFS 를 실행하였습니다.
- 거리가 K 인 지점들을 result에 담아주고 K+1 인 이상인 것들을 탐색하려고 할 때 break 를 실행하도록 해줬습니다.
- import sys 를 해서 시간 복잡도를 줄여줬습니다. 
- 수의 범위가 매우 작기 때문에 완전탐색으로 가능하다고 생각했습니다.
- 벽을 세울 수 있는 칸들을 구하고 그것의 nC3 을 구해줬습니다. 
- deepcopy 로 새로운 맵을 만들고 앞에서 구한 각각의 조합에 대하여 벽을 세운 상황을 만들었습니다.
- 바이러스들이 완전히 퍼진 상황을 BFS 을 통해서 구현해주었고, 0 의 개수를 count 하여 안전영역의 수를 구하였습니다.
=> [DFS/BFS] yunjin-0328

jaeyeon/DFSBFS/Q15-특정 거리의 도시 찾기.py, jaeyeon/DFSBFS/Q16-연구소.py
- 특정 거리의 도시 찾기
- 연구소
---
- 풀이과정
1. 인접 리스트로 이어진 도시 찾기
2. BFS로 순회하면서 최단 거리 업데이트
- 풀이과정
1. 벽을 세울 수 있는 모든 조합 구하기
2. 모든 조합에 대해서 벽을 세우고, 바이러스를 BFS로 퍼트리기
3. BFS가 끝나면 안전 구역 개수 세기
4. 각 조합에 대한 최대 안전 구역 개수 업데이트
=> [DFS/BFS] jaeyeon-0328

youngjun/DFSBFS/연구소.py, youngjun/DFSBFS/특정 거리의 도시 찾기.py
- 문제 1 특정 거리의 도시 찾기
- 문제 2 연구소
---
- 인접리스트 생성
- 현재 도시와 cnt를 queue에 넣어서 bfs 돌림
- cnt를 1씩 추가하며 k와 같은 곳은 answer에 추가
- 벽을 설치하는 모든 경우의 수로 설치
- 이후에 바이러스를 bfs로 퍼뜨리기
- 0 개수 세서 answer 업데이트
- bfs로 2로 바꾸는 과정에서 제대로 작동이 안되는 것 같음
---
- 2번 문제 while문에서 어디가 문제인지 모르겠는데 제대로 작동이 안되네요,,, 계속 보느라 조금 늦어졌습니다
++ 바꾸니까 해결됐습니다. 감사합니다! 행, 열 순서 어지럽네요,... 
---
=> [DFS/BFS] youngjun-0328

jaeyeon/DFSBFS/Q17-경쟁적 전염.py, jaeyeon/DFSBFS/Q18-괄호 변환.py
- 경쟁적 전염
- 괄호 변환
---
- 풀이과정
1. BFS의 특성상 먼저 들어간 요소에 대해서 먼저 탐색을 진행하므로, 초기화만 잘해주면 문제가 알아서 풀림
2. 입력 받을 때 바이러스를 따로 저장해두고, queue를 초기화할 때 virus의 번호 순서대로 append
3. 그 후 BFS를 time만큼 진행
- 풀이과정
1. 올바른 괄호 문자열인지 확인하는 함수를 스택을 활용하여 구현
2. 조건을 차례대로 수행하는 check 함수 구현
3. 1단계로 다시 돌아가는 과정은 재귀함수로 구현
=> [DFS/BFS] jaeyeon-0329

youngjun/DFSBFS/경쟁적 전염.py, youngjun/DFSBFS/괄호 변환.py
- 문제 1 경쟁적 전염
- 문제 2 괄호 변환
---
- x,y 부터 bfs로 탐색하면서 먼저 만나는 바이러스를 반환하는 방법으로 진행
- 같은 시간에 만났다면 제일 작은 바이러스 반환
-  반대로 하니까 시간은 적게 걸리는데 코너 케이스 찾기가 어렵네요...
- 조건에 필요한 두 개로 나누는 함수와 올바른 괄호인지 확인하는 함수 작성
- 조건에 맞게 1로 돌아갈 수 있는 재귀 함수 작성
---
=> [DFS/BFS] youngjun-0329

dahye/DFS_BFS/5_Q17_경쟁적전염.py, dahye/DFS_BFS/5_Q18_괄호변환.py
- 문제 1 경쟁적 전염
- 문제 2 괄호 변환
---
- 가장 작은 바이러스 부터 popleft하여 차례대로 퍼트림
- 한칸씩 바이러스가 퍼져야 하므로 bfs로 풀이
- 올바른 괄호 문자 여부 확인 함수 check생성
- 문제 조건대로 코드 입력, 1단계부터 다시 수행 시 재귀함수 수행
---
- 문제 1번은 아직도 채점중이라 놓친 부분은 없는지 확인하지 못했습니다.
---
=> [DFS_BFS] dahye-0329

yunjin/DFSBFS/Q20 감시 피하기.py
- 감시 피하기
---
- 저번에 풀었던 문제처럼 combinations 로 풀었습니다.
- 29 ~ 33 행 DFS 에서 선생님이 상하좌우로 모든 칸을 감시 할 수 있도록 for 문을 사용해서 인접 부분을 확장해줬습니다.
- `is_caught_dfs` 함수는 학생이 특정 선생님에게 감시를 걸렸는지 리턴하는 함수입니다.
- 특정 벽의 조합으로 만들어진  map에 대해서 모든 선생님들이 감시를 해서 학생들이 한 번도 걸리지 않는 경우가 한번이라도 발생하게 되면 Yes 를 프린트 합니다.
=> [DFS/BFS] yunjin-0330

jaeyeon/DFSBFS/Q20-감시 피하기.py
- 감시 피하기
---
- 풀이과정
1. 백트래킹을 활용하여 장애물 3개 세우는 조합 모두 구하기
2. 장애물이 3개 세워졌을 시 조건에 맞는 맵인지 확인
3. 각 방향에 대해서 한 칸씩 진행하며 장애물이 있는지 학생이 있는지 확인
4. 장애물이 있을 시 break, 학생이 있을 시 False 반환
=> [DFS/BFS] jaeyeon-0330

youngjun/DFSBFS/감시피하기.py
- 문제 1 감시피하기
---
- 모든 벽을 세울 수 있는 조합 만들고 각각의 경우마다 피할 수 있는 지 확인
- 확인할 때 행에 S T 사이에 X 이외 다른 것이 없으면 바로 False 반환하는 방식
- 전치해서 다시 확인하고 피할 수 있는 경우가 있으면 바로 Yes 출력
- 모든 조합 확인해봤을 때 없으면 No 출력
---
=> [DFS/BFS] youngjun-0330

jaeyeon/DFSBFS/Q21-인구 이동.py
- 인구 이동
---
- 풀이과정
1. union_map를 통해서 어떤 나라가 같은 연합에 있는지 확인
2. 연합에 포함돼있지 않은 나라를 찾으면 BFS를 활용하여 연합 찾기
코드 이해를 돕기 위해 아래 예시를 첨부합니다.
TC
```
4 10 50
10 100 20 90
80 100 60 70
70 20 30 40
50 20 100 10
```
```
union_map
[0, 1, 2, 2]
[2, 2, 2, 2]
[2, 2, 2, 2]
[2, 2, 3, 2]
```
```
map_
[10, 100, 50, 50]
[50, 50, 50, 50]
[50, 50, 50, 50]
[50, 50, 100, 50]
```
```
union_map
[0, 1, 1, 2]
[0, 1, 3, 4]
[5, 6, 7, 8]
[9, 7, 7, 7]
```
```
map_
[30, 66, 66, 50]
[30, 66, 50, 50]
[50, 50, 62, 50]
[50, 62, 62, 62]
```
```
union_map
[0, 0, 1, 1]
[1, 1, 1, 2]
[1, 1, 1, 1]
[1, 1, 3, 1]
```
```
map_
[48, 48, 54, 54]
[54, 54, 54, 50]
[54, 54, 54, 54]
[54, 54, 62, 54]
```
```
[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]
```
마지막 날의 경우 연합의 개수와 나라의 개수가 같으므로 인구 이동이 일어나지 않고 종료됩니다.
=> [DFS/BFS] jaeyeon-0331

yunjin/DFSBFS/Q21 인구 이동.py
- 인구 이동
---
- `is_population_all_same`함수는 모두 인구수가 같은지 확인하는 함수입니다. 국가의 인구수가 모두 같으면 종료합니다.
-  `population_move_dfs` 함수는 dfs 를 이용해서 특정 국가에서 인구 이동을 실시합니다. 이것을 반복문을 이용해서 특정 날짜에 진행 될 수 있는 인구 이동을 모두 진행을 해서 is_updated (인구 이동 여부)를 체크해줍니다.
- 한 번도 이동이 없었다면 해당 날짜로 종료합니다.이동이 있었다면 다음 날을 진행합니다.
=> [DFS/BFS] yunjin-0331

dahye/DFS_BFS/5_Q21_인구이동.py
- 문제 1 인구이동
---
-  bfs로 상하좌우로 이동하면서 연합이 가능한 나라들 저장
- 하나의 연합이 끝나면 bfs탈출하고 for문으로 다음 연합을 찾는다.
- 모두가 연합에 들어가면 (check_list에 더이상 0이 없으면) 인구이동
- 인구이동이 더이상 이루어지지 않으면 data_list에 같은 데이터가 쌓임 -> break
---
- 답이 이상하여 확인해보니 나라 인구수 update해줄때 필요한 list인 union_list에 값이 append가 안되어 고쳐보다 우선 업로드합니다.
---
=> [DFS_BFS] dahye-0331

youngjun/DFSBFS/인구 이동.py
- 문제 1 인구이동
---
- 연합을 0 ~ (n*n  - 1) 까지 만들고
- bfs를 통해 조건에 맞으면 같은 연합으로
- 같은 연합끼리 인구를 나누고 data를 업데이트
- 만약 이동이 없었다면 break
---
- 답은 맞게 나오는거 같은데 시간초과가 뜹니다... 아마 인구 분배하는 곳에서 시간을 많이 잡아먹는 것 같아요
---
=> [DFS/BFS] youngjun-0331

yunjin/정렬/두 배열의 원소 교체.py, yunjin/정렬/성적이 낮은 순서로 학생 출력하기.py, yunjin/정렬/위에서 아래로.py
- 위에서 아래로
- 성적이 낮은 순서로 학생 출력하기
- 두 배열의 원소 교체
---
- 파이썬 기본 라이브러리 사용하여 풀이했습니다.
- lambda 를 이용해서 정렬해주었습니다.
- 배열 A, B 를 오름차순으로 정렬해주고 sum(A) 에서 A 는 i=0 부터 커지는 방향으로  제거하고 B 는 N 번째부터 작아지는 방향으로 더해주는 방식으로 값을 바꿔주면 최대값이 나온다고 생각했습니다.
- **(추가된 내용)** left right 를 비교해서 right 가 큰 경우에만 더해줍니다. 만약 아닌 경우에는 정렬 된 상태이므로 더 이상 바꿔줘도 A 가 커지지 않으니 break 해서 더 이상 바꿔주지 않습니다.  
---
저도 잘 못 풀었습니다. left<right 비교 조건 추가하고 break 조건 추가해서 다시 커밋했습니다.
=> [정렬] yunjin-0403

dahye/정렬/6_2_위에서아래로.py, dahye/정렬/6_3_성적이낮은순서로학생출력하기.py, dahye/정렬/6_4_두배열의원소교체.py
- 문제 1 위에서 아래로
- 문제 2 성적이 낮은 순서로 학생 출력하기
- 문제 3 두 배열의 원소 교체
---
- list를 sort하여 내림차순으로 정렬한 후 print
- #점수를 key, 이름을 name으로 힌 dictionary생성하여 key를 기준으로 sorted하여 생성된 tuple에서 value를 출력
- B를 작은수부터 정렬하고 큰값을 pop하여 A에 추가
- A는 큰수부터 정렬하고 작은값을 pop하는 방식으로 합을 최대로 만들어줌
- 최대 K번실행, 더이상 합이 최대가 되지 않으면 break 
---
=> [정렬] dahye-0403

youngjun/정렬/두배열의원소교체.py, youngjun/정렬/성적이낮은순서로학생출력하기.py, youngjun/정렬/위에서아래로.py
- 문제 1 위에서 아래로
- 문제 2 성적이 낮은 순서로 학생 출력하기
- 문제 3 두 배열의 원소 교체
---
- 파이썬 기본 정렬 라이브러리를 사용해서 내림차순 정렬
- 순서대로 출력
- 딕셔너리로 이름 점수를 받고 점수를 기준으로 정렬
- key를 순서대로 출력
- A배열은 오름차순 B배열은 내림차순 정렬
- A배열 작은 값과 B배열 큰값들을 순서대로 k번 비교해가면서 A의 값이 B의 값보다 크면 break
- A배열 합 출력 
---
=> [정렬] youngjun-0403

jaeyeon/정렬/Q23-국영수.py, jaeyeon/정렬/Q24-안테나.py
- 국영수
- 안테나
---
- 풀이과정
내장 라이브러리와 lambda 함수를 통해 정렬 기준을 만들고 정렬하였습니다.
- 풀이과정
중앙값을 찾는 문제라고 생각하였고, N이 짝수일 때를 대비해서 두 가지 케이스를 비교하도록 했습니다.
=> [정렬] jaeyeon-0405

yunjin/정렬/Q23 - 국영수.py, yunjin/정렬/Q24 - 안테나.py
- 국영수
- 안테나
---
- lambda 로 정렬 처리
- position 을 순회할 때 증가하는 거리, 감소하는 거리를 r 배열에 넣어주고 정렬해서 최솟값을 리턴해줬습니다.
- **(추가)** 13,14행에서 position 을 곱해주는 게 뭔가 말이 안되네요. 지은님이 푸신 것처럼 하는게 맞는거 같습니다. postion을 빼도 통과가 되긴 하네요.
- **(추가2)** 식을 보시면은 answer = `(2*L-N)*positon` 입니다. `L = int(2/N)` 인 지점까지 감소하다가 증가하게 되는 것 같습니다. 그래서 제 생각엔 중앙값 계산하고 우연히 식이 맞아 떨어져서 통과가 되는 것 같습니다.
=> [정렬] yunjin-0405

jieun/정렬/Q23_국영수.py, jieun/정렬/Q24_안테나.py
- 국영수
- 안테나
---
- `functools.cmp_to_key`를 사용해서 비교함수를 작성해고 정렬에 사용.
- `cmp(x,y)`를 정의할 때, 
- 음수를 반환하면 순서는 x -> y
- 양수를 반환하면 순서는 y -> x
- 위치 순서대로 집 배열을 정렬.
- `dist[i]`는 i번째와 (i-1)번째 집 사이의 거리.
- `left`는 i번째 집 왼쪽의 거리 합이고 `right`는 오른쪽 거리 합
- `dist[i]`가 반복된 값을 `right`에서 빼고, `left`에 더한다.
- i번째 집에 대해 구할 때 `dist[i]`를 제외하고 거리의 합은 (i-1)번째 집과 같기 때문.
- `dist[k]`는 왼쪽에 있을 때(k<i) k번, 오른쪽에 있을 때(k>i) (N-k)번 만큼 반복해서 총 거리에 더해진다.
---
=> [정렬] jieun-0405

youngjun/정렬/국영수.py, youngjun/정렬/안테나.py
- 문제 1 국영수
- 문제 2 안테나
---
- lambda를 사용해서 조건 우선순위로 오름차순 내림차순 정렬
- 올리면서 봤는데 이름을 소문자로 바꿔서 정렬해줘야 될 것 같은데 안해도 백준 통과는 됐습니다
- 처음에는 최소 최대 중간값에 가까운 집에 설치하는 방식으로 해서 안돼서
- 중앙값에 가까운 집에 설치하는 방식으로 바꾸니까 통과
- 자세한 증명은 안되는 중...
---
- 안테나 문제 중앙값으로 했을 때 되는 이유가 궁금합니다
---
=> [정렬] youngjun-0405

dahye/정렬/6_Q23_국영수.py, dahye/정렬/6_Q24_안테나.py
- 문제 1 국영수
- 문제 2 안테나
---
- 한 조건씩 차례대로 정렬
- 집을 정렬한 후 짝수일 경우 가운데 두 집 중 하나를 뽑아서 총 거리를 비교하고 홀수일 경우 가운데 집을 뽑음
- 가운데에 위치한 집을 뽑아야 총 거리가 짧다는 점을 이용
---
- 국영수에서 lamba에 묶어서 한번에 정렬하려 하니 str앞에 -를 붙일 수 없다는 오류가 발생하여 다음과 같이 풀이하였습니다. 그런데 오답이 나오는데 이유를 모르겠습니다.
---
=> [정렬] dahye-0405

jaeyeon/정렬/Q25-실패율.py, jaeyeon/정렬/Q26-카드 정렬하기.py
- 실패율
- 카드 정렬하기
---
- 풀이과정
1. 각 스테이지 별로 사용자들이 도달한 횟수를 구합니다.
2. Counter 라이브러리로 각 스테이지에 위치하는 사용자의 수를 구합니다.
3. 조건에 맞게 실패율을 구하고 정렬합니다.
- 풀이과정
1. 힙큐를 활용하여 카드를 정렬합니다.
2. 현재 카드 목록 중에 가장 작은 두 카드를 더 하고 다시 카드 목록에 넣는 것이 최소 비교 횟수를 유도합니다.
(가장 작은 카드 두 개를 골라야 하는 건 간단한 증명을 통해서 확인하였습니다.)
현재 목록 중에서 가장 작은 두 카드를 빠르게 고르고, 새로 카드를 넣었을 때 오름차순으로 정렬될 수 있게 힙큐를 사용했습니다.
3. 힙큐에 한 카드만 남을 때까지 위 과정을 반복합니다.
원래 stack으로 pop/append 하며 구했지만, 새로 만든 카드가 가장 작은 두 카드에 포함되지 않는 경우를 발견했습니다.
그래서 우선순위큐로 다시 진행했는데, 시간초과가 나서 힙큐로 교체 했더니 됐습니다.
우선순위큐와 힙큐가 같은 기능을 하지만, 힙큐가 더 빠르니 우선 순위를 가진 큐를 구현할 땐 모두 힙큐를 사용하도록 합시다 ,,,
=> [정렬] jaeyeon-0406

yunjin/정렬/Q25 - 실패율.py, yunjin/정렬/Q26 - 카드 정렬하기.py
- 실패율
- 카드 정렬하기
---
- count 를 세서 실패율 넣어주고 정렬해서 print 해줍니다.
- 답지 참고하였습니다.
- 힙을 통해 작은 값 두개를 빼줘서 넣어주는 작업을 반복하게 되면 최소 갯수를 구할 수 있습니다.
=> [정렬] yunjin-0406

dahye/정렬/6_Q25_실패율.py, dahye/정렬/6_Q26_카드정렬하기.py
- 문제 1 실패율
- 문제 2 카드 정렬하기
---
- 스테이지 번호를 key로, 실패율을 value로 for문을 돌며 저장
- 실패율을 기준으로 sort한 후 스테이지 번호 출력
- 작은 묶음 수부터 합쳐야 최소 비교수를 구할 수 있다는 아이디어
- j번째 합치기에서 합쳐야할 카드수를 list에 저장한 후 한번에 sum을 하여 전체 비교 수를 구한다.
---
=> [정렬] dahye-0406

youngjun/정렬/실패율.py, youngjun/정렬/카드 정렬하기.py
- 문제 1 실패율
- 문제 2 카드 정렬하기
---
- 1스테이지 부터 실패율을 계산해가며 총 인원에서 실패한 사람 빼줌
- [스테이지, 실패율]을 리스트에 append
- 남은 사람이 없으면 해당 스테이지 부터 끝까지[스테이지,0] append 후 실패율,스테이지 순으로 정렬
- 힙큐에 입력받은 뒤 heappop을 통해 최솟값 두개 뽑기
- 합친 카드 묶음을 다시 힙큐에 넣어서 반복
---
=> [정렬] youngjun-0406

yunjin/implementation/Q14 외벽점검.py
- 외벽점검
---
- 감이 아예 안와서 답지 그대로입니다...
- 원형을 일자로 만듭니다.
- 각 시작점을 중심으로 모든 친구들의 순열 조합을 확인합니다.
- 친구들을 위치시켜서 최소한으로 수리할 수 있는 값을 갱신시켜 나갑니다.
- 코멘트는 안해주셔도 될거 같습니다..
=> [구현] yunjin-0407

jieun/구현/Q14_외벽점검.py
- 외벽 점검
---
1. `dist`의 permutations 중 친구들이 출발하는 순서 하나를 고른다.
2. `weak` 속 취약점 하나를 첫 출발점으로 삼는다.
3. 해당 순서로 시계방향으로만 외벽을 돌 때, 모든 취약점을 방문할 수 있는지 확인한다.
취약점은 첫 출발점에서 시계방향 순으로 방문한다.
4. 모든 취약점을 방문할 수 있으면 답을 갱신한다.
5. 모든 경우에 대해 1~4 번을 반복한다. 
시간 복잡도는 대략 8! x 15 x 15
---
실수로 main 브랜치에 푸쉬해서 PR용 커밋 날립니다. 😅 
코드 파일 보실 때 밑에 있는 화살표 버튼 두 번 정도 눌러야지 전체 코드가 나오네요.
---
=> [구현] jieun-0407 PR용

dahye/구현/4_Q14_외벽점검.py
- 문제 1 외벽 점검
---
- 친구 조합 생성하여 취약지점 탐색하는 방식
- 마지막까지 탐색된 위치보다 현재 취약 지점의 값이 크다면 친구를 추가하는 아이디어
---
- 새로 배운 heap을 사용하여 모두 탐색 후에 최소값을 return하는 풀이로 진행하였는데 풀리지않아 답안참고 하였습니다. 
---
=> [정렬] dahye-0407

youngjun/구현/외벽점검.py
- 문제 1 외벽 점검
---
- 각 지점 사이의 거리 리스트 만든 후
- 인원을 한명씩 늘릴 때 마다 각 지점 사이의 거리중 가장 큰 한 구역을 배제해도 된다는 생각에서 시작
- 한명일 수 있는 경우 부터 확인하며 인원을 한명씩 늘려나가고 모든 외벽을 갈 수 있다면 answer 리스트에 저장
- 풀이가 정리가 안돼서 설명이 부족하네요.. 고려해야될 부분이 더 있다고 생각되는데 시간이 없어서 완성은 못했습니다
---
=> [구현] youngjun-0407

dahye/DP/8_2_1로만들기.py, dahye/DP/8_3_개미전사.py
- 문제 1 1로만들기
- 문제 2 개미전사
---
- x부터 시작해서 각 숫자에 도달할때까지 연산 횟수인 d를 만들어 최소값을 저장하며 DP로 풀이
- 최소 한칸 이상 떨어진 식량창고를 약탈해야하므로 이전칸 vs 전전칸+현재칸 비교를 통해 최대값을 저장하며 DP로 풀이
---
=> [DP] dahye-0410

yunjin/dp/1로 만들기.py, yunjin/dp/개미전사.py
- 1로 만들기
- 개미 전사
---
- 백준에 비슷한 문제가 있어서 확인해봤습니다 [링크](https://www.acmicpc.net/problem/1463)
``` 
if i % 5 == 0 and i % 3 == 0 and i % 2 == 0:
dp[i] = min(dp[i-1], dp[i//5], dp[i//3], dp[i//2]) + 1
elif i % 5 == 0 and i % 3 == 0 :
dp[i] = min(dp[i-1], dp[i//5], dp[i//3]) + 1
elif i % 5 == 0 and i % 2 == 0:
dp[i] = min(dp[i-1], dp[i//5], dp[i//2]) + 1
elif i % 3 == 0 and i % 2 == 0:
dp[i] = min(dp[i-1], dp[i//3], dp[i//2]) + 1
```
이 부분을 처음에 생략했었는데 틀려서 나중에 추가해주었습니다.
- 5, 3, 2 로 나눠 떨어지면 그것과 d[i-1] 의 값을 비교해서 작은 값의 + 1을 d[i] 로 해줍니다.
- dp 로 식이 생각이 안나서 왼쪽부터 오른쪽으로 가면서 약탈가능한 값의 최댓값을 확인해 줬습니다.
- 주어진 조건은 값의 범위가 작지만 만약에 더 범위가 컸다면 시간 초과가 뜰 것 같습니다.
=> [DP] yunjin-0410

jaeyeon/DP/1로 만들기.py, jaeyeon/DP/개미전사.py
- 1로 만들기
- 개미전사
---
- 풀이과정
1. 바텀업 방식으로, dp 배열을 순회하면서 인덱스 값의 x5, x3, x2, +1의 연산을 진행하고 count 값 업데이트
2. 위 방법을 통해서 각 숫자마다 최소 연산 횟수 업데이트
**++추가**
하나의 값에 대해서 여러번 계산하는 부분이 생겨서, 이전 값들로 현재 값을 업데이트하는 방식이 DP에 더 맞을 것 같습니다,,!
다시 풀어봐야겠어요 😅
- 풀이과정
1. 현재 보고 있는 음식과 2번째 전의 음식을 고르거나, 현재 보고 있는 음식을 포기하고 직전 음식을 고르는 경우로 나눌 수 있다.
2. 두 가지 경우 중 더 많은 음식을 약탈할 수 있는 경우로 dp 배열을 업데이트
=> [DP] jaeyeon-0410

jieun/DP/1로만들기.py, jieun/DP/개미전사.py
- 1로 만들기
- 개미 전사
---
dp[i]: i를 만드는 데 필요한 최소 연산
dp[i] = min(dp[i-1], dp[i//5], dp[i//3], dp[i//2]) + 1
4가지 연산 중 가능한 경우에 대해 필요한 연산이 최소인 경우를 고른다.
dp[i]: i 번째 식량창고까지 볼 때 얻을 수 있는 식량의 최대값. 
두 경우 중 최대값을 고른다.
1. i번째 식량창고를 포함하지 않는 경우: dp[i-1]
2. i번째 식량창고를 포함하는 경우: dp[i-2] + food[i]
---
=> [DP] jieun-0410

dahye/DFS_BFS/5_Q20_감시피하기_.py
- 문제 1 감시 피하기
---
- 선생님이 학생을 만나는지 여부를 확인하는 탐지함수 check를 생성하여
- 장애물을 설치할 좌표 3곳을 골라 장애물을 설치하고, 여기서 check함수로 여부를 반환한다.
- 어느 한 반복문에서 선생님을 만나지 않는다면 YES반환
---
- 선생님을 한칸씩 이동시키면서 학생과 만나는지 확인하는 함수인 check함수에서 while문을 빠져나가기 위해 다음과 같이 작성하였는데, 이렇게 되면 S가 맨 끝에 있을때를 고려하지 못하기때문에 다시작성할 예정입니다.
---
=> [DFS_BFS] dahye-0330

youngjun/DP/1로 만들기.py, youngjun/DP/개미전사.py
- 문제 1 1로 만들기
- 문제 2 개미전사
---
- 탑다운 방식으로 재귀함수를 통해 풀이
- dp행렬의 값을 (d[index를 2,3,5로 나눈 몫], d[index-1]) 중 작은 것 + 1로 최신화
- 보텀업 방식을 사용하여 n번째 창고까지의 최대값을 dp행렬에 저장해가며 최신화
- i번째 창고의 최대값은 (i-2번째 창고 최대값 + i번째 창고 식량) 과 i-1번째 창고 최대값 중 큰값으로 저장
=> [DP] youngjun-0410

yunjin/dp/바닥공사.py, yunjin/dp/효율적인 화폐 구성.py
- 바닥공사
- 효율적인 화폐 구성
---
- i 번까지의 열을 추가 한다고 하는 것은 다음과 같다.
1) `i-2` 에 2*2 를 덮개 하나 설치
2) `i-2` 에 1*2 덮개 두개를 설치
3) `i-1` 에 1*1 덮개 하나 설치
- 총 세개의 경우의 수가 있으므로 관계식은  `dp[i] = 2 * dp[i - 2] + dp[i - 1]` 이다.
- dp 배열을 -1 로 초기화 해준다.
- 가지고 있던 money들은 1장으로 만들 수 있으므로 1로 초기화 해준다.
- 만들고 싶은 i 원의 dp 도출식은 `i-money 원이 만들 수 있었던 모든 money 경우의 최솟값 +1` 이다. 아래 코드로 처리.
```
for money in moneys:
if dp[i - money] != -1:  # 화폐 단위 하나만 추가할 수 있다면
x = min(x, dp[i - money])  # 대소비교를 해준다
```
- 갱신이 한 번도 안되었다면 i 원은 만들 수 없는 화폐이다. 
수정
```
N, M = map(int, input().split())
moneys = [int(input()) for i in range(N)]
moneys.sort(reverse=True)
dp = [100001 for i in range(100001)]
dp[0] = -1
for money in moneys:
dp[money] = 1
for i in range(0, M+1):
x = float('inf')
if i in moneys:
dp[i] = 1
continue
for money in moneys:
if i-money < 0: …
```
=> [DP] yunjin-0411

jaeyeon/DP/바닥공사.py, jaeyeon/DP/효율적인 화폐구성.py
- 바닥공사
- 효율적인 화폐구성
---
- 풀이과정
2 x 1 타일을 채우는 경우는 1개, 2 x 2 타일을 채우는 경우는 2개이므로 아래와 같은 점화식을 만들 수 있습니다.
$$a_k = a_{k-1} + 2 * a_{k-2}$$
- 풀이과정
현재 보고 있는 dp칸을 가지고 있는 동전들로 만들 수 있는지 확인하고 업데이트하므로, 아래와 같은 점화식이 만들어집니다.
$$k : dp칸, m : 동전$$
$$a_k = min(a_k, a_{k-m} + 1)$$
인덱스를 벗어나는 경우를 제외해주기 위해 try/except 구문을 사용하였습니다.
=> [DP] jaeyeon-0411

jieun/DP/바닥공사.py, jieun/DP/효율적인화폐구성.py
- [바닥 공사]
- [효율적인 화폐 구성]
---
dp[i]: 가로가 i인 바닥을 채우는 방법의 수
```
dp[i] = 
dp[i-2]    # 1x2 타일 추가하는 경우
+ dp[i-1]  # 2x1 타일 추가하는 경우
+ dp[i-2]  # 2x2 타일 추가하는 경우
```
dp[i]: i원을 만들 수 있는 최소한의 화폐 개수
```
dp[i] =
모든 화폐가치 c에 대해 
dp[i-c] + 1 중 min
```
---
=> [DP] jieun-0411

dahye/DP/8_Q31_금광.py, dahye/DP/8_Q32_정수삼각형.py
- 문제 1 금광
- 문제 2 정수 삼각형
---
- 맨위와 맨아래는 두 방향에서 올 수 있으므로 if문으로 max값 후보를 나눠줌
- 바텀업 방식으로 업데이트
- n개의 층으로 되어있는 data에 대하여 가장 밑에 층부터 한층씩 위로 올라가면서 바텀업 방식으로 최대를 구함
- d는 data를 누적값으로 업데이트하는 temp역할을 함
---
=> [DP] dahye-0412

yunjin/dp/Q31 - 금광.py, yunjin/dp/Q32 - 정수 삼각형.py
- 금광
- 정수 삼각형
---
- 맨 왼쪽열에서 오른쪽열로 가면서 최대 누적합을 갱신한다.
- n 행, m 열의 최대 누적합은 맵에 있는 존재하는 것중  (n-1 행 m-1 열), (n행 m-1 열), (n+1 행 m-1 열)의 최댓값과 n행 m 열의 값을 더한 것 이다.
- 마지막 열에서 최대값을 리턴.
- 첫번째, 마지막 열의 숫자는 그대로 넘어온다.
- 그 외의 것은 왼쪽위 오른쪽 위의 것중 최대값이 넘어오도록 처리한다. (이 때 열의 인덱스를 알맞게 처리해준다)
=> [DP] yunjin-0412

jieun/DP/Q31_금광.py, jieun/DP/Q32_정수삼각형.py
- [금광]
- [정수 삼각형]
---
- dp 테이블을 입력받은 금광으로 초기화한다.
```
dp[r][c]: r행 c열에 도착했을 때, 얻을 수 있는 금의 최대 크기
= dp[r][c]            # r행 c열에 있는 금의 크기
+ max(dp[r][c-1],     # (1) 왼쪽에서 온 경우
dp[r-1][c-1],   # (2) 왼쪽 위에서 온 경우
dp[r+1][c-1])   # (3) 왼쪽 아래에서 온 경우
```
- dp 테이블의 마지막 열에서 최대값이 답
- dp 테이블을 입력받은 정수 삼각형으로 초기화한다.
```
dp[r][c]: r번째 층 c번째 칸에 도착했을 때, 선택된 수의 합
= dp[r][c]            # r번째 층 c번째 칸에 있는 수
+ max(dp[r-1][c],     # (1) 대각선 오른쪽 위에서 온 경우
dp[r-1][c-1])   # (2) 대각선 왼쪽 위에서 온 경우
```
- dp 테이블의 마지막 행에서 최대값이 답
---
=> [DP] jieun-0412

youngjun/DP/금광.py, youngjun/DP/정수 삼각형.py
- 문제 1 금광
- 문제 2 정수 삼각형
---
- 입력받은 리스트를 2차원 리스트로 변환
- dp테이블을 생성하고 첫번째 열 입력 후 바텀업 방식으로 진행
- 위에서 오는 것, 정면에서 오는 것, 아래서 오는 것 중에 큰 것으로 더해서 진행 
- n*n 행렬에 입력
- dp 테이블 생성하고 첫번째 행 입력 후 바텀업  방식으로 진행
- d[r-1][c-1], d[r-1][c] 중 큰 것을 더해가며 진행
=> [DP] youngjun-04-12

dahye/DP/8_Q33_퇴사.py, dahye/DP/8_Q34_병사배치하기.py
- 문제 1 퇴사
- 문제 2 병사 배치하기
---
- i번째 날까지 받을 수 있는 금액의 최대 값 d 생성
- i번째 날로부터 term만큼의 이전의 날에서 money를 더해줌
- 상담을 퇴사전까지 할 수 없는 경우 고려
- 0번부터 i번째 병사중 참여할 수 있는 최대 병사 수를 저장하는 d 생성
- 앞에 전투력이 큰 병사가 있을 때 어느 병사(i) 뒤에 참여할지를 max로 업데이트
---
- 문제 2에서 같은 전투력을 가진 병사에 대하여 처리를 고민하다가 부등호를 빼주니 해결되었는데, 가능한 이유를 모르겠습니다.
---
++ (수정) temp로 초기부분과 퇴사전까지 상담할 수 없을때를 max로 업데이트하는 부분을 추가하였습니다. 더 고려할 테스트케이스가 있는것같은데 다른분들 풀이 참고해보면서 파악해보겠습니다!
++ (수정) 여러분들의 소중한 피드백으로 [퇴사] 풀이했습니다. 지은님 커멘트대로, 마지막 N+1인덱스까지 계산하였더니 통과네요! 감사합니다..♡
=> [DP] dahye-0413

yunjin/dp/Q33 - 퇴사.py, yunjin/dp/Q34 - 병사 배치하기.py
- 퇴사
- 병사 배치하기
---
- 1차 반복문으로 날짜를 순차적으로 처리해나가면서
- 2차 내부 반복문에서 i 번째 날짜가 상담 마감일인 것들만 확인해서 최대로 얻을 수 있는 조합을 dp 로 갱신 시켜나간다.
- 1차 반복문으로 주어진 병사들을 한명씩 추가해나가면서
- 2차 내부 반복문에서 내림차순이 되는 조합을 확인하면서 dp 배열에 해당 지점에서 내림 차순이 되는 길이의 최대값을 갱신 시켜 나간다. 
- N 에서 dp 의 최댓값을  뺌으로써 최소 열외 인원을 구한다.
=> [DP] yunjin-0413

jaeyeon/DP/Q33-퇴사.py, jaeyeon/DP/Q34-병사 배치하기.py
- 퇴사
- 병사 배치하기
---
- 풀이과정
1. 마지막날부터 거꾸로 탐색하며, i 일부터 일했을 때의 최대 수익을 계산한다.
- 풀이과정
1. 기본 아이디어는 가장 긴 증가하는 부분 수열(Longest Increasing Subsequence)
2. 이를 응용하여 가장 긴 감소하는 부분 수열로 바꿔서 풀이
3. dp[i]의 값은 i번째 병사로 끝나는 가장 긴 부분 수열의 길이이다.
4. 왼쪽 병사부터 탐색하는 중첩 반복문에서, i 번째 병사는 본인 앞에 있는 병사들 j를 모두 탐색하며 본인보다 전투력이 높으면서, 가장 긴 감소 부분 수열을 만들 수 있는 부분 수열에 붙는다고 생각하면 된다.
=> [DP] Jaeyeon-0413

youngjun/DP/병사 배치하기.py, youngjun/DP/퇴사.py
- 문제 1 퇴사
- 문제 2 병사 배치하기
---
- N일 부터 퇴사 전에 끝낼 수 있는 작업 확인
- d[i] = max(d[i+day]+money,d[i+1]) 을 통해 최대값을 계속 최신화
- d[0] 출력 
- 해당 병사와 그전 병사들을 비교해서 제일 긴 곳으로 이어 가는 느낌
- 풀이가 생각이 안 나서 답지 확인했는데도 이해하는 데 오래 걸리네요..
---
=> [DP] youngjun-0413

youngjun/DP/바닥 공사.py, youngjun/DP/효율적인 화폐 구성.py
- 문제 1 바닥 공사
- 문제 2 효율적인 화폐 구성
---
- i-2 번째 경우에서 2x2 한개 놓는 경우
- i-2 번째 경우에서 1X2 두개 놓는 경우
- i-1 번째 경우에서 2X1 두개 놓는 경우
-  d[i] = (d[i-2] * 2) + d[i-1]
- dp 테이블을 -1로 만들고 d[0]을 0으로
- 각 단위별로 d[0] 부터 더해줌
- d[i]가 -1 이면 continue
---
=> [DP] youngjun-0411

youngjun/DP/못생긴수.py, youngjun/DP/편집거리.py
- 문제 1 못생긴 수
- 문제 2 편집거리
---
- n의 범위가 크지않고 못생긴 수가 아닌 숫자가 그렇게 많지 않을 것 같아서 while문으로 직접 n번째 못생긴 수 찾는 방법사용
- 시간이 생각보다 안걸리는 것 같습니다
- 너무 안풀려서 풀이 참고했습니다..!
- 따로 코멘트 안주셔도 될 것 같습니다!
---
=> [DP] youngjun-0414

yunjin/dp/Q35 - 못생긴 수.py, yunjin/dp/Q36 - 편집 거리.py
- 못생긴 수
- 편집 거리
---
- 주어진 수를 2, 3, 5로 나누는 while 문을 만든다.
- 한번이라도 나눠지면 계속 반복하는데, 나누는 과정에서 1이 되는 경우가 존재한다면 해당 수는 2,3,5 로 만 이뤄진 못생긴수다.
- 풀이 참고했습니다. 코멘트 안해주셔도 됩니다.
- 리트코드에서 풀이 보다가 bfs 로 푼 경우가 있어서 해당 경우로 올려봤습니다.
- bfs 는 깊이 단위로 진행이 되고 각 반복문마다 삭제, 교체, 추가 하는 경우를 모두 큐에 넣음으로써 최소인 경우를 체크할 수 있게 되는 것 같습니다.
=> [DP] yunjin-0414

jaeyeon/DP/Q35-못 생긴 수.py, jaeyeon/DP/Q36-편집 거리.py
- 못 생긴 수
- 편집 거리
---
- 풀이과정
현재 값을 2 또는 3 또는 5로 나눈 값이 못 생긴 수라면 현재 값 또한 못 생긴 수라는 점을 이용해서 구하기.
- 풀이과정
DP로는 어떻게 풀어야할 지 아예 감이 안 와서 다른 방법으로 풀었습니다.
풀이 아이디어는, 각 문자열에서 가장 긴 공통 부분 문자열(LCS)을 제거한 후에 남는 문자열에 대해서 연산 횟수를 계산하는 것입니다.
LCS 알고리즘은 [이 블로그](https://my-coding-notes.tistory.com/279)를 참고했습니다.
lcs : 가장 긴 부분 문자열
removed : lcs 제거 후 남은 문자열 쌍(만약 값이 있다면 연산 진행)
만약 lcs의 길이가 n이라면 총 n+1 개의 문자열 쌍이 만들어집니다.
removed 배열 내의 각 문자열 쌍의 요소는 
lcs를 제거했기 때문에 겹치는 글자가 없으며,
요소 둘 중에서 작은 길이를 s, 긴 길이를 l 라고 한다면
s번만큼 수정을 진행하고, (l-s)번만큼 추가 또는 삭제를 진행해야합니다.
따라서 각 요소별 진행 횟수는 두 요소 중 더 긴 요소의 길이와 같습니다.
예시 케이스들과 함께 풀이 남깁니다.
cat 
cut
```
lcs : ct
removed : [['', ''], ['a', 'u'], ['', '']]
answer : 1
```
sunday
saturday
```
lcs : suday
removed : [['', ''], ['', 'at'], ['n', 'r'], ['', ''], ['', ''], ['', '']]
answer : 3
```
october …
=> [DP] jaeyeon-0414

dahye/DP/8_Q35_못생긴수.py, dahye/DP/8_Q36_편집 거리.py
- 문제 1 못생긴 수
- 문제 2 편집 거리
---
- 못생긴 수는 2,3,5를 곱하여 만드는 수라는 점을 이용
- d는 못생긴 수 저장공간
- temp는 못생긴 수를 작은 수부터 뽑기 위한 임의 heap
- heappop이 최소값을 return한다는 점을 이용하여 반복문 수행
- d[i][j]는 A의 j번째 단어가 B의 0부터 i번째 단어가 되기 위한 편집거리 수
- d[i-1][j] -> 삭제 / d[i][j-1] -> 삽입 / d[i-1][j-1] -> 교체 이 중 작은것을 선택
- A의 j번째 단어와 B의 i번째 단어가 같으면 교체할 필요 없음
---
- 문제 2는 감이 잡히지 않아 2차원 list로 해결하는 아이디어를 참고하였습니다.
---
=> [DP] dahye-0414

jieun/이진탐색/떡볶이떡만들기.py, jieun/이진탐색/부품찾기.py
- 부품찾기
- 떡볶이 떡 만들기
---
이진 탐색을 다음 구조로 수행함:
```
while lo + 1 < hi:
mid = (lo + hi) // 2
if check(lo) == check(mid): lo = mid
else: hi = mid
```
- 가게의 부품을 오름차순으로 정렬
- check(x) : arr[x] >= target
- 각 가게의 부품에 대한 check값의 형태: FFFTTT
- check(x) = T인 최솟값(target에 대한 lower_bound)은 이진 탐색 끝나고 hi에 저장됨.
- lo,hi 초기값: 0, max(떡 높이)+1
- check(h) : 절단기 높이가 h일 때 잘린 떡의 길이 합 >= M
- 각 높이에 대해 check 값은 TTTFFF 의 형태를 띔
- check(x) = T인 최댓값을 찾으면 되니까 답은 이진 탐색 끝나고 lo에 저장된 값
---
- 참고한 글: https://www.acmicpc.net/blog/view/109
---
=> [이진탐색] jieun-0417

yunjin/이진탐색/떡볶이 떡 만들기.py, yunjin/이진탐색/부품 찾기.py
- 부품찾기
- 떡볶이 떡 만들기
---
- 이진 탐색으로 매 부품마다 존재하는 지 여부를 확인합니다.
- 풀이 참고 하였습니다. 코멘트는 생략 해주시면 됩니다!
=> [이진탐색] yunjin-0417

youngjun/이진탐색/떡볶이 떡 만들기.py, youngjun/이진탐색/부품찾기.py
- 문제 1 부품찾기
- 문제 2  떡볶이 떡 만들기
---
- 오름차순으로 정렬 후 이진탐색
- 가운데가 찾는 부품보다 크다면 왼쪽 작다면 오른쪽 탐색
- 있으면 yes 없으면 no 반환 
- 가장 긴 길이를 end로 이진 탐색
- 잘린 떡의 길이가 m보다 크다면 오른쪽 작다면 왼쪽 탐색
- 마지막 mid값 반환
---
=> [이진탐색] youngjun-0417

jaeyeon/이진탐색/떡볶이 떡 만들기.py, jaeyeon/이진탐색/부품찾기.py
- 부품 찾기
- 떡볶이 떡 만들기
---
- 풀이과정
1. 이진 탐색으로 손님이 요청한 부품 찾기
- 풀이과정
1. 떡의 최대 길이 범위까지 0~maxlen 만큼의 range 배열(절단기의 높이)을 만들고, 이 배열로 이진탐색 진행
2. bisect 라이브러리를 통해 현재 떡 중에서 현재 절단기의 높이보다 높은 떡의 가장 첫번째 인덱스를 구하고, 이 인덱스보다 인덱스가 큰 떡에 한해서만 자르기 진행
3. upper bound를 구하기 위하여 자른 값이 M보다 크거나 같다면 start 인덱스를 당겨오고, 아니면 end를 당겨온다.
자른 떡의 길이를 구하는 과정에서도 이진 탐색을 사용하여 보다 빠르게 자른 떡의 길이를 구합니다.
=> [이진탐색] jaeyeon-0417

yunjin/이진탐색/Q27 - 정렬된 배열에서 특정 수의 개수 구하기.py, yunjin/이진탐색/Q28 - 고정점 찾기.py
- 정렬된 배열에서 특정 수의 개수 구하기
- 고정점 찾기
---
- bisect 를 이용해서 개수를 구합니다.
- 오름차순으로 주어졌고, 인덱스와 값이 같은것을 찾아야 하므로 값이 인덱스보다 크면 좌측으로, 반대면 우측으로 이동해서 이진탐색 처리해줍니다.
=> [이진탐색] yunjin-0418

dahye/이진탐색/7_Q27_이진탐색.py, dahye/이진탐색/7_Q28_고정점찾기.py
- 문제 1 정렬된 배열에서 특정 수의 개수 구하기
- 문제 2 고정점 찾기
---
- mid값과 target인 x가 같으면 mid를 기준으로 양옆에 모두 x가 존재 가능하므로
- 재귀를 통해 x가 존재하면 전역변수인 count에 1씩더하면서 구하는 방식으로 풀이
- mid와 인덱스가 같은지 이진 탐색(반으로 쪼개면서 탐색하기)
- mid와 인덱스가 같으면 고정점
---
=> [이진탐색] dahye-0418

jieun/이진탐색/Q27_정렬된배열에서특정수의개수구하기.py, jieun/이진탐색/Q28_고정점찾기.py
- 정렬된 배열에서 특정 수의 개수 구하기
- 고정점 찾기
---
- bisect_right로 upper_bound를 찾고, bisect_left로 lower_bound를 찾아서 뺀다.
- lo, hi : 배열의 인덱스
- arr[mid] >= mid를 만족하는 최소 mid를 찾는다. (FFFTTT 양상)
---
=> [이진탐색] jieun-0418

youngjun/이진탐색/고정점 찾기.py, youngjun/이진탐색/정렬된 배열에서 특정 수의 개수 구하기.py
- 문제 1 정렬된 배열에서 특정 수의 개수 구하기
- 문제 2 고정점 찾기
---
- 이진탐색으로 찾고자 하는 숫자 있는 지 확인 후 index 저장
- 그 index기준으로 이진탐색으로 lowerbound, upperbound 찾아서 개수 구하기
- 이진탐색으로 nums[mid] < mid 면 오른쪽
- 아니면 왼쪽을 탐색하며 고정점 찾기
---
=> [이진탐색] youngjun-0419

jaeyeon/이진탐색/Q27-정렬된 배열에서 특정 수의 개수 구하기.py, jaeyeon/이진탐색/Q28-고정점 찾기.py
- 정렬된 배열에서 특정 수의 개수 구하기
- 고정점 찾기
---
- 풀이과정
특정 값의 lower bound와 upper bound를 찾으면 되는 문제라서, bisect 라이브러리를 활용했습니다.
- 풀이과정
수열은 정렬되어 있고 만약 고정점이 있다면 이진 탐색을 통해 인덱스와 값의 비교를 통해 범위를 줄이며 찾을 수 있습니다.
인덱스와 값을 비교하며, 값이 인덱스보다 크면 인덱스를 낮춰야하고, 값이 인덱스보다 크면 인덱스를 높여야한다는 점에서 착안했습니다.
=> [이진탐색] jaeyeon-0419

yunjin/이진탐색/Q29 - 공유기 설치.py, yunjin/이진탐색/Q30 - 가사 검색.py
- 공유기 설치
- 가사 검색
---
- 풀이 그대로입니다.
- 공유가 갯수가 C 개가 될 때까지 설치를 하게 되는데. 이 때 사용하는 기법이 이진탐색이다. 양쪽 끝에 설치를 해준다음 그 중간 지점을 (mid) 로 갱신해나간다. (소수가 될 수 있는거 같다) 그 과정에서 모든 집들을 차례로 방문하면서 이전에 설치한 공유기와의 거리가 mid 보다 크다면 공유기를 설치해도 무방하다. 그 외의 경우엔 설치하면 안된다.
- 이 반복문 (29~32) 가 지나고 나서 공유기의 개수가 C 개 이상이라면 거리가 너무 좁다는 뜻이므로 mid의 값을 좁혀주기 위해 start 를 옮기는 이진탐색을 실시. 반대는 end 를 좁힘. (?)
- 이진 탐색 탈출 조건에서 공유기 사이의 최장거리가 보장됨 (?)
- 코멘트 생략해주시면 됩니다.
- 이코테 풀이입니다.
- ? 를 a, z 로 적절히 치환해서 모두 탐색할 수 있게 바꿔 준 다음 bisect 를 통해 개수를 구함. 
- 코멘트 생략해주시면 됩니다.
=> [이진탐색] yunjin-0421

dahye/이진탐색/7_Q29_공유기설치.py, dahye/이진탐색/7_Q30_가사검색.py
- 문제 1 공유기 설치
- 문제 2 가사 검색
---
- 공유기 사이의 거리인 mid에 대하여 가장 처음집부터 공유기를 설치하여 총 설치한 공유기 수를 count 해줌
- 공유기 설치 완료 or 더 많이 설치하였다면 간격(mid) 늘리기
- 공유기 설치 더 해야한다면 간격(mid) 줄이기
- bisect로 해당 단어 개수 구하는 함수 func 생성
- 단어를 길이 순으로 분리하기위해 딕셔너리 생성
- 단어 길이 순으로 분리
- 앞에 ?가 붙은 경우와 뒤에 ?가 붙은 경우를 나누어 func로 개수를 세어줌 (<- 이 부분을 이해하지 못함)
---
- 두 문제 모두 구글링하여 풀이 참고하였습니다. 코멘트 따로 안남겨주셔도 됩니다.
---
=> [이진탐색] dahye-0421

jaeyeon/이진탐색/Q29-공유기 설치.py, jaeyeon/이진탐색/Q30-가사 검색.py
- 공유기 설치
- 가사 검색
---
- 풀이과정
답지 풀이를 참고했습니다,,!
공유기를 한대씩 설치해보면서 가장 멀리 떨어트려 놓을 수 있게끔
max gap를 기준으로 이진 탐색을 진행합니다.
++ 코멘트는 안 주셔도 될 것 같습니다.
- 풀이과정
1. 이진 탐색으로 물음표의 시작과 끝 위치 구하기
2. 나머지 부분 비교
효율성 테스트 1,2,3번에서 시간 초과가 납니다 🥲
=> [이진탐색] jaeyeon-0421

yunjin/최단거리/미래 도시.py, yunjin/최단거리/전보.py
- 미래 도시
- 전보
---
- 그래프 초기화 시 양방향 관계에 맞게 처리
- 플로이드 워셜로 거리 최단 거리 초기화
- K 를 거쳐서 갈 수 있는 지 여부를 확인하고 INF 면 -1 출력.
- 다익스트라를 실시 했을 때 무한대로 남아있는 것들은 탐색 불가능 한것. 
- 최대한 많은 도시로 메시지를 보냄 -> 최단거리로 탐색 -> 다익스트라 처리.
=> [최단경로] yunjin-0424

jieun/최단경로/미래도시.py, jieun/최단경로/전보.py
- 미래 도시
- 전보
---
- 1번 -> K번 -> X번 가야 하고, 도로는 양방향.
- K에서 시작하는 다익스트라로 K -> 1 , K -> X 인 거리 두 개를 구해서 더함.
- 도시 C에서 시작하는 다익스트라로 각 도시에 전보가 도달하는 최소 시간 구함
- 도시 C를 제외한 각 도시의 최소 시간 중 최대가 답 (INF 제외)
---
=> [최단경로] jieun-0424

jaeyeon/최단경로/미래 도시.py, jaeyeon/최단경로/전보.py
- 미래 도시
- 전보
---
- 풀이과정
1에서 K, K에서 X로 가는 거리를 저장해둬야 하므로 플로이드 워셜을 알고리즘 채택했습니다.
- 풀이과정
한 지점에서 다른 지점으로의 거리만 알면 되므로 다익스트라 알고리즘을 채택했습니다.
=> [최단경로] jaeyeon-0424

youngjun/최단경로/미래 도시.py, youngjun/최단경로/전보.py
- 문제 1 미래 도시
- 문제 2 전보
---
- n이 크지 않기 때문에 플로이드 워셜 알고리즘을 통해 모든 최단 경로를 구한다.
- 1->k 최단경로 k -> x 최단경로를 더한 후 출력한다.
- n이 크기 때문에 다익스트라 알고리즘을 통해 c도시에서 갈 수 있는 최단경로를 구한다.
-  distance 테이블에서 갈 수 있는 도시의 개수와 최대 시간을 출력한다.
---
=> [최단경로] younjun-0424

yunjin/최단거리/Q37 - 플로이드.py, yunjin/최단거리/Q38 - 정확한 순위.py
- 플로이드
- 정확한 순위
---
- 플로이드 워셜 적용
- 그래프에서 특정 성분이 INF 가 아니라는 것은 어떤 i -> j 가 연결 되어 있다는 것임. -> 대소 비교 가능함
- j -> i 가 연결 되어도 대소 비교 가능한 것이므로 둘 중 하나만 INF 아니면 됨.
- 특정 학생에 대해서 이런 경우가 N 명 있으면 순위를 알 수 있다. (본인포함)
=> [최단경로] yunjin-0425

jaeyeon/최단경로/Q37-플로이드.py, jaeyeon/최단경로/Q38-정확한 순위.py
- 플로이드
- 정확한 순위
---
- 풀이과정
그래프의 초기값들을 설정하는 부분에서 중복된 값을 최소값만 저장하는 부분을 제외하고는
플로이드워셜 알고리즘 풀이와 같습니다.
- 풀이과정
본인의 순위를 알기 위해서는 위로 몇 명, 아래로 몇 명인지 알아야합니다.
이를 그래프로 해석하면 특정 노드에서 자기가 갈 수 있는 노드의 개수, 자기한테 도착할 수 있는 노드의 개수로 볼 수 있습니다.
두 경우를 합했을 때 (전체 노드의 수 - 1) 과 같다면 본인의 순위를 정확히 알 수 있습니다.
플로이드워셜 알고리즘을 실행한 후, 각 노드에 대해서 graph의 요소값이 0, INF가 아닌 값의 개수만 세줬습니다.
=> [최단경로] jaeyeon-0425

jieun/최단경로/Q37_플로이드.py, jieun/최단경로/Q38_정확한순위.py
- 플로이드
- 정확한 순위
---
- 노선이 여러 개일 수 있으므로 입력 받은 거리를 원래 dist[a][b]와 비교해서 최소로 갱신
- `dist[i][j]` : 도시 i에서 j로 가는데 필요한 최소 비용. 플로이드 와살로 채운다.
- `dist` 출력. INF이면 0 출력.
- `dist[a][b]` : 성적이 a < b 이면 1, 그렇지 않으면 0. 플로이드 와살로 채운다.
- `dist[i][a] = 1` 또는 `dist[a][i] = 1` 인 i 총 개수가 N-1이면 a의 성적 순위를 정확히 알 수 있다.
---
=> [최단경로] jieun-0425

dahye/최단경로/9_Q37_플로이드.py, dahye/최단경로/9_Q38_정확한순위.py
- 문제 1 플로이드
- 문제 2 정확한 순위
---
- 다익스트라 알고리즘을 수행하여 i번째 줄에는 도시 i가 각각의 도시에 가는데 필요한 최소 비용 출력
- 입력에서 등수가 a < b 의 의미를 가지므로 graph[a][b]에 1을 입력하여 a,b순위 차이를 입력
- 순위 차이를 기반으로 플로이드 워셜 알고리즘을 수행
- a를 기준으로 a번째열과 a번째 행을 보있을 때 다른 숫자들과 순위차이가 모두 존재한다면 a의 순위를 알 수 있음을 이용하여 count해줌
---
- 문제1은 플로이드 아닌 방법으로 시도했는데 시간초과 나네요 ㅎㅎ
---
=> [최단경로] dahye-0425

yunjin/최단거리/Q39 - 화성 탐사.py, yunjin/최단거리/Q40 - 숨바꼭질.py
- 화성 탐사
- 숨바꼭질
---
- 동서남북만 연결된 다익스트라를 적용한다.
- 양방향 거리 1 인 그래프를 만들어 다익스트라를 적용해준다.
=> [최단경로] yunjin-0426

jaeyeon/최단경로/Q39-화성탐사.py, jaeyeon/최단경로/Q40-숨바꼭질.py
- 화성 탐사
- 숨바꼭질
---
- 풀이과정
인접한 네 칸을 이어진 칸으로, 배열의 값을 cost로 생각하고 예제들과 똑같이 다익스트라 알고리즘을 수행하였습니다.
@lectura7942 덕분에 input 값 손쉽게 넣었습니다 감사합니다 🙇🏻‍♂️
- 풀이과정
다익스트라 알고리즘으로 1번 헛간으로부터 다른 헛간들까지의 거리를 모두 구하고 문제에 맞는 출력을 하였습니다.
=> [최단경로] jaeyeon-0426

youngjun/최단경로/숨바꼭질.py, youngjun/최단경로/화성탐사.py
- 문제 1 화성 탐사
- 문제 2 숨바꼭질
---
- 상하좌우 좌표, 그 좌표에 있는 값을 도착지점과 비용으로 보고 다익스트라 알고리즘으로 풀이
- 각각의 테스트 케이스에서의 distance 테이블의 [n-1][n-1] 값 출력
- 왕복으로 간선입력 후 다익스트라 알고리즘으로 풀이
- max,index,count 사용해서 정답 출력
---
=> [최단경로] youngjun-0426

jieun/최단경로/Q39_화성탐사.py, jieun/최단경로/Q40_숨바꼭질.py
- 화성 탐사
- 숨바꼭질
---
- (0,0)에서 시작하는 다익스트라로 각 칸에 도달하는데 필요한 최소 비용을 구한다.
- 1번 헛간에서 시작하는 다익스트라로 각 헛간까지 최단 거리를 구한다.
- 가장 먼 최단거리와 그 거리를 갖는 헛간들의 개수를 구한다.
---
=> [최단경로] jieun-0426

dahye/최단경로/9_Q39_화성탐사.py, dahye/최단경로/9_Q40_숨바꼭질.py
- 문제 1 화성탐사
- 문제 2 숨바꼭질
---
- 2차원 list를 1차원으로 입력받음
- 다익스트라 알고리즘으로 1부터 출발하여 최소 비용을 구하는 함수를 생성하여 결과 출력 
- 다익스트라 알고리즘을 수행하여 1에서부터 각각의 최단거리 구하기
- 최단거리 중 가장 큰값, 해당 헛간 번호, 해당 값과 동일한 값의 개수 출력
---
++ 문제2에서 시간초과 발생하네요 ...
++ 여러분들의 커멘트 덕분에 시간초과 해결했습니다! 감사합니다 ㅎㅎ
=> [최단경로] dahye-0426

yunjin/programmers/프로그래머스 - 광고삽입.py
- 광고삽입
---
1. 첫번째 시도 -> 일단 피어세션 동안 풀었을 때는 이코테 이진탐색에서 봤던 떡볶이 떡 만들기랑 공유기 설치랑 비슷해보여서 이진 탐색으로 해보려고 했습니다. 특정 지점에 가장 많이 누적되는 곳을 찾아서 구간을 탐색해주는 방법을 시도.
2. 두번째 시도 -> 누적합하는 부분, str 에서 time 으로 바꿔주는 부분 인터넷에서 확인하고 완전탐색으로 시도 -> 시간 초과.
3. 정답 풀이 다시 확인 -> DP로 시청 시작, 마감 시간을 체크해주고 DP 를 순회하면서 해당 초에 누적 시청자 구해주고 adv_time 만큼 돌아가면서  max 값을 구해주기.
=> [programmers] yunjin-04-28

jieun/광고삽입.py
- 광고 삽입
---
구간별 시청자 수 구하는 아이디어가 떠오르지 않아서 😭 검색하고 풀었습니다. 
- 시간은 초로 변환한다.
- `cnt[s]`: 구간 [s, s+1)에 보고 있는 시청자 명수
- 각 동영상 마다 cnt[시작시각] += 1, cnt[종료시각] -= 1
- 누적합을 구한다.
- 0 부터 시작해서 adv_time 만큼의 구간에 cnt 값 합을 구한다. (슬라이딩 윈도우)
- 그 값이 최대가 되는 시작 시각을 출력
📌 첫 시도 (시간 초과)
- 00:00:00 부터 99:59:59 까지 공익 광고를 삽입해보면서 최대 누적 시간을 구한다.
- 시간은 `Time` class 새로 정의해서 처리
---
=> [programmers] jieun-04-28

youngjun/programmers/광고 삽입.py
- 문제 1 광고삽입
---
- 리스트에 누적 시청 인원 전부 더해줘서 직관적으로 풀이
- 광고 시작 시간을 로그 시작 지점, 종료 지점을 기준으로 완전 탐색
- 시간 초과.. 
---
- 로그 수가 너무 많네요... 풀이 참고해서 다시 풀어보겠습니다
---
=> [programmers] youngjun-0428

dahye/random/230426_광고삽입.py
- 문제 1 광고 삽입
---
- 초단위로 계산
- 시청자의 시청 시작 시간을 광고의 시작 시간으로 설정하여
- (시청 시작 시간 + 공익광고 재생시간)을 구하여 시청 종료 시간과 비교를 통해 누적 재생시간을 구한다.
- 누적 재생시간이 큰 값이 들어오면 업데이트
---
- 테스트케이스 3개는 통과했는데 정확성이 9.7이네요 ㅎㅎ..
- 풀이과정중에 느낀건데, 시청 시작 시간을 기준으로 했으니 시청 종료 시간을 기준으로 또 계산해야할 것 같아요. 그래도 시간초과는 면하지 못할 것 같네요! 
---
=> [programmers] dahye-0428

jieun/그래프/도시분할계획.py, jieun/그래프/커리큘럼.py, jieun/그래프/팀결성.py
- 팀 결성
- 도시 분할 계획
- 커리큘럼
---
- `sz[x]`: x가 루트 노드인 집합의 크기. 1로 초기화.
- `Find(x)`: x가 속한 집합의 루트 노드를 반환.
- `Union(x,y)`: x가 속한 집합과 y가 속한 집합을 합진다.
- 경로 압축을 할 때, 계산을 줄이기 위해서 크기가 큰 집합에 크기가 작은 집합을 합친다.
- 모든 마을을 연결하는 최소 스패닝 트리를 구한다.
- 비용이 가장 큰 간선 하나를 제거한다.
- `time[x]`: x 번 강의 시간
- `ins[x]`: x번 노드(강의)로 들어가는 간선 개수
- `need_time[x]`: x 번 강의를 수강하기까지 걸리는 최소 시간.  
- 각 선수 과목의 `need_time` 중 최대값 + x 번 강의 시간  
- 선수과목 -> 후속과목 관계를 하나의 간선으로 본다.
- 위상정렬을 하면서 `need_time`을 구한다.
---
=> [그래프] jieun-05-02

yunjin/그래프/도시 분할 계획.py, yunjin/그래프/커리큘럼.py, yunjin/그래프/팀결성.py
- 팀결성
- 도시 분할 계획
- 커리큘럼
---
- `find_parent`, `union_parent` 함수를 만들어 풀이 
- 크루스칼 알고리즘을 적용하여 최소 신장 트리를 만들어준다. 그리고 최대값을 빼주면 마을을 두 개로 나누되 최솟값을 구할 수 있다.
- 위상 정렬을 적용한다. while q 문에서 누적 cost 를 넣어준다. 특정 노드에서 pop 을 실행할 때 result 에 누적 cost 를 넣어준다. ( 책 풀이하고는 차이가 있네요. 출력 결과 대로 나오기는 합니다. )
=> [그래프] yunjin-0502

dahye/그래프이론/10_2_팀결성.py, dahye/그래프이론/10_3_도시분할계획.py, dahye/그래프이론/10_4_커리큘럼.py
- 문제 1 팀결성
- 문제 2 도시분할계획
- 문제 3 커리큘럼
---
- 개선된 서로소 집합 알고리즘으로 같은팀 여부를 확인
- 최소 신장 트리로 전체 최소 유지비를 구한 후 두 도시로 분할한 후의 유지비가 최소를 구하기 위해 가장 큰 길을 제거
- 원래 계획했던 풀이가 잘 안되어 답지 참고했습니다. 커멘트 생략해주시면 될 것 같아요!
---
- 문제3 커리큘럼에서 -1값을 마지막으로 입력받는 이유가 궁금합니다. -1을 입력받지 않고 실행하니 결과가 달라지네요.
+추가 리스트 슬라이싱에서 맨 마지막은 포함이 안된다는것을 깜빡했네요 ㅎㅎ 커멘트 감사합니다!
---
=> [그래프이론] dahye-0502

youngjun/그래프/도시 분할 계획.py, youngjun/그래프/커리큘럼.py, youngjun/그래프/팀 결성.py
- 문제 1 팀 결성
- 문제 2 도시 분할 계획
- 문제 3 커리큘럼
---
- 책에 나와있는 개선된 서로소 집합 알고리즘 사용해서 풀이하였습니다
- 첫 입력이 1일 때만 find_union 함수 사용해서 정답 출력
- 책에 나와있는 크루스칼 알고리즘을 통해서 신장트리 구한 후 최대 길이 도로 빼기
- 거리가 가장 큰 간선이 마지막에 추가되기 때문에 마지막 값 빼주기
- 위상정렬 응용이 아직 어려워서 풀이 참고했습니다
---
거의 다 책 참고해서 풀이해서 코멘트 따로 안주셔도 됩니다!
=> [그래프] youngjun-0502

yunjin/그래프/Q41 - 여행 계획.py, yunjin/그래프/Q42 - 탑승구.py
- 여행 계획
- 탑승구
---
- 여행 가능한 지점에 대해서 
- 그래프의 모든 1 지점에 대해서 union 실시
- 여행 계획 코스의 루트들을 집합에 넣어서 길이가 1이 아니라면 NO 출력, 1 이라면 YES 출력 
- 코멘트 생략 하시면 됩니다! 
- 책 풀이 참고. -> union 할 때 자신보다 1 만큼 작은 수와 union 을 하게 되면 find 가 재귀적으로 돌아가므로 누적된 지점 까지 루트를 연결할 수 있게 된다. 0 까지 루트가 되었다는 것은 해당 수 만큼 비행기가 찼다는 뜻. 만약 특정 수가 0 까지 루트 노드 연결이 된다면 더 이상 비행기를 넣을 수 없게 된다.
- 기존 풀이 
-  주어진 input 값을 0 과 union 을 해준다. 
- 자신 보다 작은 모든 값들의 루트를 확인해서 모두 0 을 가지고 있다면 더 이상 비행기를 넣을 수 없을거라는 방식으로 코드를 짰다.   
-  이 때 num_cnt_list 를 구해서 특정 수가 몇번 나왔는 지 체크해주고 그 만큼 차감하는 부분도 들어감. 
- 이렇게 하게 되면 이미 union 된 수는 생략해주는 부분이 없어서 수의 범위가 작더라도 오답일 듯 하다. 
- 리스트를 집합으로 바꾸는 시간 복잡도 N 에 N 을 반복하게 되므로 10**10 시간 복잡도를 가짐. 
```python
for i in range(P):
input_number = numbers[i]
if set(parent[1 : input_number + 1]) == set([0]):         
break
else:
union_parent(parent, …
```
=> [그래프] yunjin-0503

dahye/그래프이론/10_Q41_여행계획.py, dahye/그래프이론/10_Q42_탑승구.py
- 문제 1 여행 계획
- 문제 2 탑승구
---
- 서로소 집합 알고리즘으로 각 여행지가 도로로 연결되어있는지 확인하면서 여행 가능한지 체크
- 문제를 이해하지 못하여 답지 참고 했습니다. 특히 'i번째 비행기에 대하여 1부터 g_i번째 탑승구에 도킹할 수 있다'에서 g_i의 의미를 이해하지 못했습니다. 피어세션 시간에 얘기 나눠보면 좋을 것 같아요. 커멘트 생략해주시면 될 것 같습니다!
---
=> [그래프] dahye-0503

jaeyeon/그래프/Q41-여행 계획.py, jaeyeon/그래프/Q42-탑승구.py
- 여행 계획
- 탑승구
---
- 풀이과정
방문한 여행지를 한 번 더 방문할 수 있으므로 단순한 서로소 집합 문제라고 생각했습니다.
양방향 행렬을 입력 받기 때문에 겹치는 부분이 생겨, 우측 상삼각행렬만 탐색하도록 코드를 짰습니다.
그 외에는 전형적인 서로소 집합 풀이입니다.
- 풀이과정
위상정렬 방식으로 풀고 싶었지만 도저히 풀이 설계를 못 하겠어서 포기했습니다.
그리디한 방식으로 푼 것 같다는 느낌이 듭니다.
1. 각 비행기들이 들어갈 수 있는 탑승구 번호 입력 받기
2. 각 비행기들은 들어갈 수 있는 탑승구 번호 중 가장 큰 탑승구에 도킹한다는 전제 하에 문제 풀이 
-> 최대한 많은 비행기를 도킹할 수 있는 최적해 보장
3. 정렬된 배열 안에서 현재 값이 이 전 값보다 크면 이전 값에서 -1를 해주는 식으로 업데이트
-> 번호가 큰 탑승구부터 차례대로 도킹하기 때문에 큰 번호의 탑승구는 이미 도킹이 되었으므로 (이전값 -1) 로 업데이트
시간 복잡도는 O(N)으로, 시간초과는 나지 않을 것 같고 반례를 찾지 못해서 지금까진 맞는 풀이인 것 같습니다.
+++ 백준에 제출해보니 틀렸다고 뜨네요 좀 더 봐야할 것 같습니다 🥲
=> [그래프] jaeyeon-0503

youngjun/그래프/여행 계획.py, youngjun/그래프/탑승구.py
- 문제 1 여행계획
- 문제 2 탑승구
---
- 행렬에서 i,j가 1이면 i+1 -> j+1 간선처리
- 그 후 서로소 집합 알고리즘
- 입력받은 g번에 가깝게 비행기 도킹
- find_union(parent,g)를 통해 g번에 가까운 자리부터 채워나갈 수 있음
- 도킹 후 토킹한 자리와 -1번 자리 union 처리
- 답은 제대로 나오는 거 같은데 시간 초과 나네요..
++ find에서 압축이 안됐었네요.. 수정했습니다! @JLake310 코멘트 감사합니다
=> [그래프] youngjun-0503

jaeyeon/그래프/Q43-어두운 길.py, jaeyeon/그래프/Q44-행성 터널.py
- 어두운 길
- 행성 터널
---
- 풀이과정
크루스칼 알고리즘으로 최소 신장 트리 구해서 풀었습니다! 
- 풀이과정
첫 풀이는 메모리 초과가 났습니다,,,
각 좌표에 대해서 정렬하는 아이디어는 생각했지만
배열을 복사해서 정렬하는 식으로 풀었더니 잘 안 됐네요 🥲
답지 참고해서 풀이하였고, 따로 코멘트는 안 주셔도 될 것 같습니다.
- 메모리 초과 풀이
```python
if __name__ == "__main__":
N = int(input())
positions = []
costs = []
parent = [i for i in range(N)]
for cur_idx in range(N):
cur_pos = list(map(int, input().split()))
if not positions:
positions.append(cur_pos)
else:
for pre_idx, pre_pos in enumerate(positions):
cost = 9876543210
for cur_val, pre_val in zip(cur_pos, pre_pos):
cost = min(cost, abs(cur_val - pre_val))
heappush(costs, (cost, cur_idx, pre_idx))
positions.append(cur_pos)
min_cost = 0
while costs:
cost, x, y = heappop(costs)
if find_parent(parent, x) != find_parent(parent, y):
union(parent, x, y)
min_cost += cost …
```
=> [그래프] jaeyeon-0504

jaeyeon/그래프/Q43 - 어두운 길.py, jaeyeon/그래프/Q44 - 행성 터널.py
- 어두운 길
- 행성 터널
---
- `total_sum += cost` 으로 모든 가로등 비용 더해주기
- 유니온 파인드로 result 에는 최소 신장 트리 가로등 비용 더해주기
- 빼주어 결과 출력 해주면 절약 비용 최대
- 코멘트 생략하시면 될 거 같습니다. 
- 기존 시도 -> 메모리  초과 -> 모든 행성을 연결하여 edges 에 넣어줌.
``` python
for i in range(N):
for j in range(i, N):
edges.append((min(abs(planets[i][0] - planets[j][0]),
abs(planets[i][1] - planets[j][1]),
abs(planets[i][2] - planets[j][2]))
, i, j))
```
- 답지 확인 -> 
x, y, z 를 분리해서 각각의 거리 비용을 edge 에 넣어줘서 3*N 의 시간 복잡도를 이용하였다.
```python
for i in range(N - 1):
edges.append((x[i + 1][0] - x[i][0], x[i+1][1], x[i][1]))
edges.append((y[i + 1][0] - y[i][0], y[i+1][1], y[i][1]))
edges.append((z[i + 1][0] - z[i][0], z[i+1][1], z[i][1]))
```
=> [그래프] yunjin-0504

jieun/그래프/Q43_어두운길.py, jieun/그래프/Q44_행성터널.py
- Q43 어두운 길
- Q44 행성 터널
---
- 모든 마을을 포함하는 최소 신장 트리를 찾는다.
- 답 = 전체 간선 길이 합 - 최소 신장 트리 간선 길이 합
- 모든 간선 N*N 개를 찾으면 시간 초과
- x 위치 기준으로 행성을 정렬해서 인접한 행성 간 간선 저장
- y 위치, z 위치에 대해서도 마찬가지
- 최소 신장 트리의 간선 합 출력
- 구한 간선 중 진짜 비용이 아닌 것도 있다. 그러나 최소 신장 트리에 들어가는 간선은 진짜 비용임이 보장.
---
=> [그래프] jieun-05-04

youngjun/그래프/어두운 길.py, youngjun/그래프/행성 터널.py
- 문제 1 어두운 길
- 문제 2 행성 터널
---
- 크루스칼 알고리즘을 통해 최소 금액 구해서
- 총 비용에서 최소금액을 뺀 값 출력
- 모든 간선을 구한 후 크루스칼 알고리즘
- 간선 개수가  comb(n,2)개여서 메모리 초과 문제가 납니다...
- 행성터널 문제 답지에 나와있는 간선 추리는 아이디어가 이해가 안되네요..
---
=> [그래프] youngjun-0504

dahye/그래프이론/10_Q43_어두운길.py, dahye/그래프이론/10_Q44_행성터널.py, dahye/그래프이론/10_Q45_최종순위.py
- 문제 1 어두운 길
- 문제 2 행성 터널
- 문제 3 최종 순위
---
- 크루스칼 알고리즘으로 사이클이 발생하면 비활성화하여 비용을 줄이는 방식으로 풀이
- 크루스칼 알고리즘으로 사이클이 발생하지 않는 경우에 터널을 건설하여 비용을 추가하는 방식으로 풀이
- 각각 행성들 사이의 거리를 계산하여 간선에 대한 정보로 사용
- 위상 정렬로 바꿀팀을 입력받아 graph와 진입차수를 수정하면서 진행
- 위상정렬일에서는 여러답이 나올 수 있다는 아이디어로 ?를 고려하지 않음
---
- 문제2에서 각 행성마다의 거리를 구해주는 과정에서 메모리초과 발생하는 것 같습니다.
- 문제3은 틀린풀이인데, 테스트케이스는 모두 통과됩니다. 이 부분은 피어세션시간에 다른분들 풀이 들어보면서 생각해보면 좋을 것 같습니다!
---
=> [그래프] dahye-0504

yunjin/그래프/Q45 - 최종 순위.py, yunjin/기출/Q46 - 아기 상어.py
- 최종순위
- 아기 상어
---
- 코멘트 생략하시면 됩니다.
- 실패 풀이 -> 위상 정렬로 풀면 어떻게 될꺼 같았다. 순위가 바뀌는 부분을 기점으로 나가는 부분과 들어오는 부분의 값을 조정해주고 위상 정렬해주는 방식으로 진행했다. 
impossible 부분이 
1. 순환 그래프를 생성하고 
2. 두 가지 이상의 경우의 수가 나오는 경우
라는 걸 생각하지 못했다.
```python
for i in range(len(numbers) - 1):
adj[numbers[i]].append(numbers[i + 1])
indegree[numbers[i]] += 1
print(indegree)
for i in range(len(changes)):
if changes[i][0] in adj[changes[i][1]]:
adj[changes[i][1]].remove(changes[i][0])
adj[changes[i][1]].append(numbers[i][1])
indegree[changes[i][1]] -= 1
adj[changes[i][0]].append(changes[i][1])
indegree[changes[i][0]] += 1
```
- 정답 풀이 : 
1. 순위가 바뀌는 부분을 처리해준다.
2. 순환 그래프인지, 정렬 결과가 여러개이면 IMPOSSIBLE 출력
----
- 코멘트 생략하시면 됩니다.
- 실패 풀이
-> 일단 수의 범위가 매우 작아서 BFS 로 풀려고 했다.
그런데 BFS 를 하면서 상단, 좌측 의 우선순위를 주기 위해서 어떻게 해야 하는지 감이 안잡혔다.
그래서 아래 그림처럼 
거리 1 …
=> [기출] yunjin-0508

jieun/그래프/Q45_최종순위.py, jieun/기출/Q46_아기상어.py
- Q45 최종 순위
- Q46 아기 상어
---
- x 팀 등수가 y 팀 등수보다 높은 것을 간선 x -> y 로 표현
- 작년 등수를 간선으로 표현하고, 올해 바뀐 등수를 간선에 반영.
- 위상정렬하면서 올해 순위 저장
- 큐에 원소가 2개 이상 있으면 확실한 순위를 모른다 --> "?"
- 올해 순위에 모든 팀이 저장되어 있지 않으면 사이클이 있어서 위상정렬 빨리 끝난 것 -> "IMPOSSIBLE"
- `size`: 상어 크기; `ate`: 현재 상어 크기일 때 먹은 물고기 개수; `time`: 시간
- 상어가 위치한 칸의 값을 INF로 바꾼다.
- `find_food()`로 먹을 물고기 위치와 거기까지 가는 이동 시간을 구한다.
- 상어 주변을 bfs로 탐색
- heapq를 사용해서 탐색하는 칸의 순서를 거리, y좌표(r), x좌표(c) 오름차순으로 유지.
- 먹을 물고기를 찾았으면 `ate`, `time`을 갱신한다. 상어 크기만큼 물고기를 다 먹었으면 `size += 1`, `ate = 0`
- 먹을 물고기를 못 찾으면 while문을 멈추고 `time`을 출력한다.
---
=> [기출] jieun-0508

youngjun/기출/아기상어.py
- 문제 1 최종순위
- 문제 2 아기상어
---
- 위상 정렬 문제인지도 몰라서 못풀었습니다
- 첫번째 풀이
- bfs로 상 좌 우 하 순서로 탐색하면 처음 만나는 먹을 수 있는 물고기가 우선순위라고 생각함
- 상 좌 우 하 순서로 하면 우선순위가 제대로 안 됨
- 두번째 풀이
- bfs로 같은 거리의 먹을 수 있는 물고기 전체를 구함
- 만약 여러개라면 sort로 우선순위 물고기 찾음
---
@JLake310  코멘트 참고해서 수정하니까 확실히 빨라지고, 메모리 줄어드네요 time은 빼니까 깊이 계산이 안돼서 size, eat를 큐에서 빼고 can_eat배열을 힙큐로 사용했습니다
=> [기출] youngjun-0508

jieun/기출/Q47_청소년상어.py
- Q47 청소년 상어
---
- 공간을 4x4 행렬로 표현. 각 칸 값은 (물고기, 방향)
- 큐에 `(공간 상태, 먹은 물고기 합, 상어 위치)` 저장하면서 bfs 수행
- `move_fish()`로 물고기를 이동시킨 후, 상어가 먹을 수 있는 물고기의 모든 경우를 큐에 집어넣는다.
- `move_fish()`: 현재 공간 상태에서 모든 물고기가 이동하고 난 후의 새로운 공간 상태을 반환
- 공간을 돌면서 각 물고기의 위치 찾기
- 번호 순으로 물고기 이동
---
=> [기출] jieun-05-09

yunjin/기출/Q47 - 청소년 상어.py
- 청소년 상어
---
- 리뷰 생략하시면 될 거같습니다.
- 기존 실패 풀이  :: 
- 상어가 갈 수 있는 공간 마다  simul 함수 호출한다. 이후 원복 코드
- 한 번도 움직이지 못한 경우를 탈출조건으로 줘서 백트래킹을 구현하고자 했으나 탈출 조건이 제대로 작동하지 않는 듯 하다.
```python
if map_[nr][nc][0] != 0:
dead.append(map_[nr][nc][0])
u = map_[nr][nc][0]
eating += u
map_[nr][nc][0] = 99
map_[r][c][0] = 0
flag = True
simul(nr, nc, map_[nr][nc][1], eating, dead)
eating -= u
map_[r][c][0] = 99
map_[nr][nc][0] = 0
dead.pop()
if not flag:
result.append(eating)
return
```
- 정답 풀이 ::
- move_all_fishes 함수를 이용해서 물고기 이동을 한번에 처리.
- get_possible_positions 이라는 함수를 이용해서 상어가 갈 수 있는 영역을 구함.  
- 상어 이동 영역이 없으면 종료 (탈출조건) 하고, 영역이 존재하면 dfs 를 재귀적으로 호출 처리.
=> [기출] yunjin-0509

jaeyeon/삼성/Q47-청소년 상어.py
- 청소년 상어
---
- 풀이과정
1. 물고기들의 위치를 따로 배열에 저장해두고 사용하기
2. 물고기 이동시키는 함수로 물고기 이동하기
3. 백트래킹/BFS로 상어 이동하기
4. 2로 돌아가서 상어 이동 못 할때까지 진행하기
---
- 백준 예제 중에서 나머지는 값이 잘 나오는데 3번만 242라는 값이 나와서 채점은 못 해봤습니다,,! 어디서 이런 터무니 없는 값이 나오는지 못 찾았네요 🥲
---
=> [기출] jaeyeon-0509

youngjun/기출/청소년 상어.py
- 문제 1 청소년 상어
---
- 물고기 1번 부터 움직이는 함수 생성
- dfs를 통해 모든 경우의 수 돌리고, answer 제일 큰 것으로 최신화
---
- 최대한 해결하려고 했는데 안풀리네요.... 틀린 곳을 못찾겠습니다.............
- 해결했습니다... dfs문 안에 초기화 문제였네요
---
=> [기출] youngjun-0509

jaeyeon/삼성/Q48-어른 상어.py
- 어른 상어
---
- 풀이과정
1. 현재 방향과 우선 순위 고려해서 상어가 다음에 이동할 위치 구하기
2. 상어 번호대로 이동시켜서 격자 밖으로 쫓아낼 상어 구하기
3. 냄새의 위치를 저장해둔 deque 리스트를 이동하여 시간이 k보다 크면 하나씩 pop 하며 지워주기
- 테케 2번이 오답이 나와서 제출할 엄두를 못 냈네요 ,,
---
=> [기출] jaeyeon-0511

jieun/기출/Q48_어른상어.py
- Q48 어른 상어
---
- `arr[N][N]`: 격자 위 상어 번호 기록
- `time_arr[N][N]`: 격자 위 최근 냄새가 뿌려진 시각 기록
- `priority[M+1][5][4]`: 상어별 방향별 우선순위
- `shark[M+1]`: 각 상어의 위치, 방향 저장
- `time`: 현재 시각
- 상어와 방향 인덱스는 1부터 시작하게 하기 위해 패딩 적용
`time`이 하나 증가할 때마다 다음 과정 반복.
1. `get_new_pos()`로 각 상어가 이동할 칸을 찾는다.
- `key: 칸 위치`, `value: (상어, 방향) 리스트`를 갖는 dict 반환
- 방향 우선순위에 따라서 먼저 냄새 없는 칸 탐색 후 자기 냄새 있는 칸 탐색.
2. `arr`, `tmp_arr`, `shark` 갱신. 
- 한 칸에 여러 마리 상어가 있으면 (상어,방향) 리스트 속 첫 번째 상어 외는 제거
4. 격자에 상어 몇 마리가 남았는지 확인
- 한 마리면 break
- `time` >= 1000면 break ( *>로 생각해서 계속 틀렸었다* )
---
=> [기출] jieun-0511

youngjun/기출/어른상어.py
- 문제 1 어른상어
---
- 상어위치, 방향, 냄새 정보, 우선순위를 담고 있는 각각의 객체를 만들고
- 상어 1번부터 우선순위로 움직이고 만약 상어가 겹치면 뒤에 들어온 상어를 삭제
- 냄새 정보 행렬에서 1씩 뺀 후 상어들이 새로 도착한 곳에 냄새 정보 최신화
- 상어가 한마리 남을 때 반복문 탈출
---
- 백준 질문 게시판에 있는 반례들까지 잘 돌아가는데 제출만 하면 바로 틀린다고 나옵니다...
---
=> [기출] youngjun-0511
